const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(value,lang)=>Array.isArray(value)?value[lang==='en'?1:0]:value;
const n=(x,y,label,sub='',w=145)=>({x,y,label,sub,w});
const row=(labels)=>labels.map((label,i)=>n(22+i*178,80,label));
const configs={
 fundamentals:{title:['AI 안에서 ML, 그 안에서 딥러닝','AI contains ML; ML contains deep learning'],caption:['개념의 포함 관계를 단순화한 도식입니다. 모든 AI가 머신러닝이나 LLM인 것은 아닙니다.','A simplified hierarchy. Not every AI system is machine learning or an LLM.'],kind:'hierarchy'},
 'data-and-generalization':{title:['데이터를 나누는 세 가지 목적','Three roles for dataset splits'],caption:['분할 비율을 나타내는 그림이 아닙니다. 테스트 데이터는 모델 선택이 끝날 때까지 분리해 둡니다.','Box sizes do not represent split ratios. Keep test data separate until model selection is complete.'],nodes:[n(288,15,['데이터셋','Dataset']),n(30,115,['학습 세트','Training set'],['가중치 갱신','Update weights'],190),n(265,115,['검증 세트','Validation set'],['모델·설정 선택','Select model & settings'],190),n(500,115,['테스트 세트','Test set'],['최종 평가','Final evaluation'],190)],edges:[[0,1],[0,2],[0,3]]},
 training:{title:['학습의 반복 과정','The training loop'],caption:['역전파는 기울기를 계산하고, 옵티마이저는 가중치를 갱신합니다. 갱신한 모델로 다음 배치를 처리합니다.','Backpropagation computes gradients; the optimizer updates weights before the next batch.'],nodes:row([['순전파','Forward pass'],['손실 계산','Compute loss'],['역전파','Backpropagation'],['가중치 갱신','Update weights']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'neural-networks':{title:['층을 통과하며 변하는 표현','Representations across layers'],caption:['완전연결 신경망의 예시입니다. 원은 뉴런, 선은 학습되는 연결을 나타냅니다.','An example of a fully connected network. Circles are neurons; lines represent learned connections.'],kind:'network'},
 evaluation:{title:['무엇을 맞히고, 무엇을 놓쳤을까?','What was detected, and what was missed?'],caption:['양성은 찾으려는 대상입니다. 정밀도는 TP/(TP+FP), 재현율은 TP/(TP+FN)입니다.','Positive means the target class. Precision = TP/(TP+FP); recall = TP/(TP+FN).'],kind:'matrix'},
 'tokens-and-embeddings':{title:['텍스트에서 벡터까지','From text to vectors'],caption:['토큰 분할과 ID는 토크나이저에 따라 달라집니다. ID의 크기가 의미적 유사도를 나타내지는 않습니다.','Token boundaries and IDs depend on the tokenizer. ID magnitude does not indicate semantic similarity.'],nodes:row([['텍스트','Text'],['토큰화','Tokenization'],['토큰 ID','Token IDs'],['임베딩 벡터','Embedding vectors']]),edges:[[0,1],[1,2],[2,3]]},
 transformer:{title:['Attention의 정보 흐름','Information flow in attention'],caption:['Q와 K로 관계 점수를 계산하고, softmax 가중치로 V를 결합합니다. 위치별·헤드별 계산은 생략했습니다.','Q and K produce scores; softmax weights combine V. Per-position and per-head details are omitted.'],nodes:[n(20,25,'Q'),n(20,140,'K'),n(220,80,['관계 점수','QKᵀ / √dₖ']),n(420,80,'softmax'),n(420,195,'V'),n(610,80,['가중합','Weighted sum'],'',130)],edges:[[0,2],[1,2],[2,3],[3,5],[4,5]],height:300},
 'llm-inference':{title:['다음 토큰을 하나씩 이어 쓰기','Generate one token at a time'],caption:['선택한 토큰을 문맥에 붙이고 반복합니다. 종료 토큰이나 길이 제한에 도달하면 멈춥니다.','Append the selected token to the context and repeat until a stop token or length limit.'],nodes:row([['현재 문맥','Current context'],['모델 계산','Model forward pass'],['다음 토큰 선택','Select next token'],['문맥에 추가','Append to context']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 rag:{title:['검색 자료를 근거로 답변하기','Ground answers in retrieved sources'],caption:['문서 색인은 검색에 쓰이고, 검색 결과는 질문과 함께 모델에 전달됩니다. 모델 가중치를 갱신하는 과정은 아닙니다.','The index supports retrieval. Retrieved passages and the question enter the model; weights are not updated.'],nodes:[n(25,15,['문서 색인','Document index']),n(25,130,['질문','Question']),n(220,75,['관련 문서 검색','Retrieve passages']),n(415,75,['질문 + 근거','Question + context']),n(610,75,['모델 답변','Model answer'],'',130)],edges:[[0,2],[1,2],[2,3],[1,3],[3,4]],height:235},
 'fine-tuning':{title:['LoRA: 원본 가중치와 작은 변화량','LoRA: base weights plus a small update'],caption:['기본 가중치 W를 고정하고 A·B를 학습합니다. 실제 구현의 스케일 계수는 생략한 구조도입니다.','Freeze W and train A and B. This structural diagram omits the implementation’s scaling factor.'],nodes:[n(25,90,['입력 x','Input x']),n(240,25,['기본 가중치 W','Frozen weights W'],['고정','Frozen'],195),n(230,155,'A',['학습','Trainable'],105),n(380,155,'B',['학습','Trainable'],105),n(570,90,['Wx + BAx','Wx + BAx'],['출력','Output'],160)],edges:[[0,1],[0,2],[2,3],[1,4],[3,4]],height:270}
};
Object.assign(configs,{
 'linear-regression':{title:['특성의 가중합으로 수치 예측','Predict a number from weighted features'],caption:['입력 특성에 학습한 가중치를 곱하고 편향을 더합니다. 예측과 실제 값의 차이를 손실로 측정합니다.','Multiply features by learned weights, add bias, and compare the prediction with the target.'],nodes:row([['입력 특성 x','Input features x'],['가중합 wᵀx + b','Weighted sum'],['수치 예측 ŷ','Prediction ŷ'],['실제 값과 비교','Compare with target']]),edges:[[0,1],[1,2],[2,3]]},
 'logistic-regression':{title:['확률 추정과 최종 판정 구분하기','Separate probability from the decision'],caption:['Sigmoid는 선형 점수를 0~1로 바꿉니다. 임계값은 확률 추정 이후에 적용하는 별도 선택입니다.','Sigmoid maps a linear score to (0,1). The decision threshold is a separate choice.'],nodes:row([['선형 점수 z','Linear score z'],['Sigmoid','Sigmoid'],['확률 추정 p','Estimated p'],['임계값으로 판정','Apply threshold']]),edges:[[0,1],[1,2],[2,3]]},
 'decision-trees':{title:['질문과 답을 따라 리프로 이동','Follow conditions to a leaf'],caption:['배송 예측을 설명하는 가상 규칙입니다. 실제 트리 학습은 데이터로 분기 조건을 선택합니다.','Illustrative delivery rules, not a trained model. Training selects splits from data.'],nodes:[n(285,10,['거리 ≤ 10km?','Distance ≤ 10km?'],'',180),n(95,105,['물량 ≤ 100?','Volume ≤ 100?'],['예 / Yes','Yes'],180),n(510,105,['느림','Slow'],['아니오 / No','No'],150),n(25,205,['빠름','Fast'],['예 / Yes','Yes'],140),n(245,205,['보통','Normal'],['아니오 / No','No'],140)],edges:[[0,1],[0,2],[1,3],[1,4]],height:290},
 clustering:{title:['K-means의 반복','The K-means loop'],caption:['K를 정하고 중심점에 배정한 뒤 평균으로 중심을 갱신합니다. 초기화와 특성 스케일에 따라 결과가 달라집니다.','Choose K, assign points, and update means. Initialization and feature scaling affect the result.'],nodes:row([['K·초기 중심 선택','Choose K & centers'],['가까운 중심에 배정','Assign nearest'],['군집 평균 계산','Compute means'],['중심 갱신·반복','Update & repeat']]),edges:[[0,1],[1,2],[2,3]]},
 'activation-functions':{title:['ReLU를 통과하는 값','Values passing through ReLU'],caption:['ReLU(x)=max(0,x). 음수는 0이 되고 양수는 유지됩니다. 다른 활성화 함수는 다른 변환을 사용합니다.','ReLU(x)=max(0,x). Negative values become zero; positive values pass through.'],nodes:[n(45,85,'[-2, 0, 3]',['입력','Input'],190),n(285,85,'ReLU',['max(0, x)','max(0, x)'],190),n(525,85,'[0, 0, 3]',['출력','Output'],190)],edges:[[0,1],[1,2]]},
 cnn:{title:['CNN에서 공간 크기와 채널 변화','Spatial size and channels in a CNN'],caption:['예시: 3×3 필터 16개, stride 1, valid padding. 배치 축은 생략했습니다.','Example: 16 filters of size 3×3, stride 1, valid padding. The batch axis is omitted.'],nodes:row([['32 × 32 × 3','32 × 32 × 3'],['Conv 3×3 / 16','Conv 3×3 / 16'],['30 × 30 × 16','30 × 30 × 16'],['ReLU','ReLU']]),edges:[[0,1],[1,2],[2,3]]},
 rnn:{title:['같은 셀, 시간에 따라 바뀌는 상태','Shared cell, evolving hidden state'],caption:['모든 시간 단계에서 가중치를 공유합니다. 현재 입력과 이전 상태를 함께 사용해 다음 상태를 만듭니다.','Weights are shared across time. Each step combines its input with the previous state.'],nodes:[n(25,90,'h₀'),n(215,90,'RNN → h₁'),n(405,90,'RNN → h₂'),n(595,90,'RNN → h₃'),n(215,190,'x₁'),n(405,190,'x₂'),n(595,190,'x₃')],edges:[[0,1],[1,2],[2,3],[4,1],[5,2],[6,3]],height:275},
 regularization:{title:['데이터 손실에 가중치 페널티 더하기','Add a weight penalty to data loss'],caption:['L2 정규화의 예시입니다. λ는 검증 데이터로 조절하며, dropout이나 조기 종료와는 다른 기법입니다.','L2 example. Tune λ on validation data; dropout and early stopping are different techniques.'],nodes:[n(45,30,['데이터 손실','Data loss'],'L data',180),n(45,140,['가중치 페널티','Weight penalty'],'λ Σ w²',180),n(310,85,['합산','Sum'],'L total',170),n(545,85,['최적화','Optimize'],['가중치 갱신','Update weights'],170)],edges:[[0,2],[1,2],[2,3]]}
});
Object.assign(configs,{
 'cs-data-representation':{title:['문자가 바이트로 저장되는 과정','Encoding a character as a byte'],caption:['문자 A의 UTF-8 바이트는 01000001입니다. 같은 비트열을 부호 없는 정수로 읽으면 65입니다. 해석 규칙에 따라 의미가 달라집니다.','The UTF-8 byte for A is 01000001. Interpreted as an unsigned integer, these bits mean 65. Meaning depends on interpretation.'],nodes:row([['문자 A','Character A'],['UTF-8 인코딩','UTF-8 encoding'],'01000001',['정수로 읽으면 65','As an integer: 65']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-computer-architecture':{title:['저장장치에서 CPU까지','From storage to CPU'],caption:['필요한 데이터를 메모리로 가져와 사용하는 흐름을 단순화했습니다. 캐시에 있는 데이터는 RAM을 다시 읽지 않아도 됩니다.','A simplified path for loading and using data. A cache hit avoids another RAM access.'],nodes:row([['저장장치','Storage'],['RAM','RAM'],['캐시','Cache'],['CPU · 레지스터','CPU · registers']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-data-structures':{title:['스택과 큐의 꺼내는 순서','Stack and queue removal order'],caption:['A, B, C 순서로 넣었습니다. 스택은 마지막 항목부터, 큐는 첫 항목부터 꺼냅니다.','Insert A, B, C in that order. A stack removes the last item first; a queue removes the first item first.'],nodes:[n(30,90,'A → B → C'),n(280,25,['스택 · LIFO','Stack · LIFO']),n(280,150,['큐 · FIFO','Queue · FIFO']),n(550,25,'C → B → A'),n(550,150,'A → B → C')],edges:[[0,1],[0,2],[1,3],[2,4]]},
 'cs-algorithms-complexity':{title:['이진 탐색은 후보를 반씩 줄입니다','Binary search halves the candidates'],caption:['정렬된 데이터에서 한 번 비교할 때마다 남은 탐색 범위를 대략 절반으로 줄입니다. 마지막 화살표는 여러 비교를 생략한 것입니다.','In sorted data, each comparison roughly halves the remaining range. The final arrow omits several comparisons.'],nodes:row(['1,024','512','256',['… → 1','… → 1']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-networking':{title:['웹 요청의 큰 흐름','A simplified web request'],caption:['주소 확인, 연결, 요청, 응답의 개념도입니다. 캐시·연결 재사용·TLS 협상과 HTTP 버전별 세부 차이는 생략했습니다.','Address resolution, connection, request and response. Caches, connection reuse, TLS negotiation and HTTP version differences are omitted.'],nodes:row([['DNS 주소 확인','DNS lookup'],['서버 연결','Connect to server'],['HTTP 요청','HTTP request'],['HTTP 응답','HTTP response']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-databases':{title:['키로 두 테이블 연결하기','Join two tables using keys'],caption:['users.id와 orders.user_id가 같은 행을 연결하는 예시입니다. 한 사용자가 여러 주문을 가지면 결과에도 여러 행이 생깁니다.','Match users.id to orders.user_id. A user with multiple matching orders appears in multiple result rows.'],nodes:[n(25,25,'users','id · name',185),n(25,150,'orders','user_id · item',185),n(300,85,'JOIN','id = user_id',180),n(550,85,['결과 행','Result rows'],'name · item',180)],edges:[[0,2],[1,2],[2,3]]},
 'cs-transactions-indexes':{title:['여러 변경을 하나로 확정하기','Commit multiple changes together'],caption:['송금의 차감과 입금을 하나의 트랜잭션으로 묶습니다. 모두 성공하면 COMMIT하고, 실패하면 ROLLBACK으로 변경을 취소합니다.','Group debit and credit in one transaction. COMMIT on success; ROLLBACK discards the changes on failure.'],nodes:row(['BEGIN',['계좌 A 차감','Debit account A'],['계좌 B 입금','Credit account B'],'COMMIT']),edges:[[0,1],[1,2],[2,3]]},
 'cs-concurrency':{title:['갱신 하나가 사라지는 경쟁 상태','A lost update'],caption:['초기 값은 0입니다. 두 작업이 각자 1을 더하지만, 읽기와 쓰기가 원자적이지 않아 최종 값이 기대한 2 대신 1이 됩니다.','Start at 0. Two tasks each add 1, but non-atomic read–modify–write operations leave 1 instead of the expected 2.'],nodes:row([['A: 0 읽기','A: read 0'],['B: 0 읽기','B: read 0'],['A: 1 쓰기','A: write 1'],['B: 1 쓰기','B: write 1']]),edges:[[0,1],[1,2],[2,3]]}
});
Object.assign(configs,{
 'os-kernel-system-calls':{title:['프로그램이 커널에 서비스를 요청하기','Requesting a kernel service'],caption:['필요한 시스템 콜을 수행하는 흐름입니다. 라이브러리 내부에서 처리되는 호출은 커널에 들어가지 않을 수 있으며, 모드 전환이 반드시 스레드 교체를 뜻하지는 않습니다.','A call requiring kernel service. Some library calls stay in user mode; a mode transition does not necessarily switch threads.'],nodes:row([['프로그램','Application'],['라이브러리','Library'],['시스템 콜 · 커널','System call · kernel'],['결과 반환','Return result']]),edges:[[0,1],[1,2],[2,3]]},
 'os-processes-threads':{title:['I/O를 기다렸다가 다시 실행하기','Waiting for I/O and becoming ready'],caption:['준비 → 실행 → I/O 대기 → 준비의 단순화한 흐름입니다. 대기가 끝나도 CPU를 다시 배정받아야 실행됩니다. 선점·종료 등의 전이는 생략했습니다.','Ready → running → waiting for I/O → ready. Becoming ready still requires scheduling. Preemption and exit transitions are omitted.'],nodes:row([['준비','Ready'],['실행','Running'],['I/O 대기','Blocked on I/O'],['다시 준비','Ready again']]),edges:[[0,1],[1,2],[2,3]]},
 'os-cpu-scheduling':{title:['시간을 나누어 번갈아 실행하기','Round-robin time sharing'],caption:['A와 B가 각각 CPU 4ms를 필요로 하고 시간 할당량은 2ms인 예시입니다. 전환 비용과 I/O는 생략했습니다.','A and B each need 4 ms of CPU time with a 2 ms quantum. Context-switch overhead and I/O are omitted.'],nodes:row(['A · 0–2 ms','B · 2–4 ms','A · 4–6 ms','B · 6–8 ms']),edges:[[0,1],[1,2],[2,3]]},
 'os-virtual-memory':{title:['가상 페이지를 물리 프레임으로 연결','Mapping a virtual page to a physical frame'],caption:['페이지 크기 4,096바이트, 가상 페이지 2 → 물리 프레임 7인 예시입니다. 오프셋 8은 유지되어 물리 주소는 28,680입니다. TLB와 다단계 조회는 생략했습니다.','Example: 4,096-byte pages, virtual page 2 mapped to frame 7. Offset 8 is preserved, giving physical address 28,680. TLB and multilevel lookup are omitted.'],nodes:row([['가상 주소 8,200','Virtual: 8,200'],['페이지 2 · 오프셋 8','Page 2 · offset 8'],['프레임 7로 매핑','Map to frame 7'],['물리 주소 28,680','Physical: 28,680']]),edges:[[0,1],[1,2],[2,3]]},
 'os-filesystems':{title:['파일 이름과 열린 파일 참조 구분하기','From a pathname to an open file reference'],caption:['Linux에서 파일을 여는 과정을 단순화했습니다. 경로로 파일을 찾은 뒤 열린 파일 상태를 만들고 프로세스의 디스크립터로 참조합니다.','Simplified Linux open: resolve the path, create open-file state, and refer to it through a process file descriptor.'],nodes:row([['경로','Pathname'],['VFS · 파일 찾기','VFS · resolve file'],['열린 파일 상태','Open-file state'],['파일 디스크립터','File descriptor']]),edges:[[0,1],[1,2],[2,3]]},
 'os-io-interrupts':{title:['장치 작업과 완료 처리','Device work and completion handling'],caption:['인터럽트를 사용하는 I/O 완료의 예시입니다. 캐시나 폴링을 쓰는 경로는 다를 수 있고, 준비 상태로 바뀐 스레드가 즉시 실행되지는 않습니다.','An interrupt-driven completion example. Cache and polling paths differ; a ready thread is not guaranteed to run immediately.'],nodes:row([['I/O 요청','Submit I/O'],['장치 작업','Device work'],['인터럽트 처리','Handle interrupt'],['대기 작업 깨우기','Wake waiting task']]),edges:[[0,1],[1,2],[2,3]]},
 'os-synchronization':{title:['같은 순서로 락을 획득하기','Acquire locks in a consistent order'],caption:['X와 Y를 쓰는 모든 관련 코드가 같은 획득 순서를 지키는 예시입니다. 다른 자원 대기나 예외 경로도 함께 검토해야 합니다.','All code using X and Y follows the same acquisition order in this example. Other resource waits and exception paths still need review.'],nodes:row([['X 획득','Acquire X'],['Y 획득','Acquire Y'],['공유 상태 갱신','Update shared state'],['Y · X 해제','Release Y and X']]),edges:[[0,1],[1,2],[2,3]]},
 'os-ipc':{title:['요청과 응답을 작업 ID로 연결','Match a request and response by ID'],caption:['두 프로세스가 합의한 메시지 형식으로 통신하는 예시입니다. 전달 실패·시간 제한·중복 요청 처리는 별도로 설계해야 합니다.','Two processes use an agreed message format. Delivery failures, timeouts and duplicate requests require separate handling.'],nodes:row([['A: 요청 #42','A: request #42'],['통신 채널','IPC channel'],['B: 작업 처리','B: process task'],['A: 결과 #42 수신','A: receive #42']]),edges:[[0,1],[1,2],[2,3]]}
});
function body(config,lang){
 if(config.kind==='hierarchy')return `<rect x="35" y="20" width="675" height="215" rx="16" fill="#eaf1ec" stroke="#b8ccbe"/><text x="60" y="55">AI · ${lang==='en'?'Artificial Intelligence':'인공지능'}</text><rect x="185" y="75" width="495" height="135" rx="13" fill="#dce9df" stroke="#aec4b4"/><text x="210" y="106">ML · ${lang==='en'?'Machine Learning':'머신러닝'}</text><rect x="360" y="128" width="290" height="58" rx="10" fill="#52745e"/><text x="505" y="162" text-anchor="middle" fill="white">${lang==='en'?'Deep Learning':'딥러닝'}</text>`;
 if(config.kind==='network'){
  const layers=[[65,[85,155]],[270,[50,120,190]],[480,[85,155]],[670,[120]]];let out='';
  for(let i=0;i<layers.length-1;i++)for(const y of layers[i][1])for(const yy of layers[i+1][1])out+=`<line x1="${layers[i][0]}" y1="${y}" x2="${layers[i+1][0]}" y2="${yy}" stroke="#c2d3c8"/>`;
  layers.forEach(([x,ys],i)=>{ys.forEach(y=>out+=`<circle cx="${x}" cy="${y}" r="17" fill="${i===3?'#587963':'#e3eee6'}" stroke="#91b29b"/>`);out+=`<text x="${x}" y="235" text-anchor="middle">${pick([['입력','Input'],['은닉층 1','Hidden 1'],['은닉층 2','Hidden 2'],['출력','Output']][i],lang)}</text>`;});return out;
 }
 if(config.kind==='matrix'){
  let out=`<text x="315" y="28" text-anchor="middle">${lang==='en'?'Predicted positive':'양성 예측'}</text><text x="560" y="28" text-anchor="middle">${lang==='en'?'Predicted negative':'음성 예측'}</text>`;
  [[65,'TP',['올바른 탐지','Correct detection'],'#e2eee5'],[155,'FP',['오탐','False alarm'],'#f5eee3']].forEach(([y,key,label,fill],i)=>{out+=`<text x="95" y="${y+40}" text-anchor="middle">${lang==='en'?(i?'Actual negative':'Actual positive'):(i?'실제 음성':'실제 양성')}</text>`;out+=`<rect x="195" y="${y}" width="230" height="75" rx="8" fill="${fill}"/><text x="310" y="${y+30}" text-anchor="middle">${key}</text><text class="diagram-sub" x="310" y="${y+55}" text-anchor="middle">${pick(label,lang)}</text>`;const label2=i?['올바른 제외','Correct rejection']:['미탐','Missed detection'];out+=`<rect x="440" y="${y}" width="230" height="75" rx="8" fill="${i?'#e2eee5':'#f5eee3'}"/><text x="555" y="${y+30}" text-anchor="middle">${i?'TN':'FN'}</text><text class="diagram-sub" x="555" y="${y+55}" text-anchor="middle">${pick(label2,lang)}</text>`;});return out;
 }
 let out='';
 for(const [from,to]of config.edges){const a=config.nodes[from],b=config.nodes[to];const dx=b.x+b.w/2-a.x-a.w/2,dy=b.y-a.y;const horizontal=Math.abs(dy)<80||Math.abs(dx)>250;const x1=horizontal?(dx>=0?a.x+a.w:a.x):a.x+a.w/2,y1=horizontal?a.y+30:(dy>=0?a.y+60:a.y),x2=horizontal?(dx>=0?b.x:b.x+b.w):b.x+b.w/2,y2=horizontal?b.y+30:(dy>=0?b.y:b.y+60);out+=`<path d="M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2} ${y2}" fill="none" stroke="#9bb5a3" stroke-width="1.6" marker-end="url(#arrow)"/>`;}
 if(config.loop)out+='<path d="M 630 143 V 195 H 94 V 146" fill="none" stroke="#9bb5a3" stroke-width="1.5" stroke-dasharray="5 4" marker-end="url(#arrow)"/>';
 for(const node of config.nodes){const label=pick(node.label,lang),sub=pick(node.sub,lang);out+=`<rect x="${node.x}" y="${node.y}" width="${node.w}" height="60" rx="10" fill="#edf4ef" stroke="#c5d7cb"/><text x="${node.x+node.w/2}" y="${node.y+(sub?26:35)}" text-anchor="middle">${esc(label)}</text>${sub?`<text class="diagram-sub" x="${node.x+node.w/2}" y="${node.y+46}" text-anchor="middle">${esc(sub)}</text>`:''}`;}
 return out;
}
export function diagram(slug,lang){const c=configs[slug];if(!c)return '';const title=pick(c.title,lang),caption=pick(c.caption,lang),height=c.height||260;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 ${height}" role="img" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">${esc(title)}</title><desc id="diagram-desc">${esc(caption)}</desc><style>text{font:14px system-ui,sans-serif;fill:#496852}.diagram-sub{font-size:11px;fill:#71877a}text[fill="white"]{fill:white}</style><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#9bb5a3"/></marker></defs>${body(c,lang)}</svg>`;
 return `<figure class="concept-diagram"><div class="diagram-heading"><strong>${esc(title)}</strong><a download="${slug}-${lang}.svg" href="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}">SVG ↓</a></div><div class="diagram-scroll">${svg}</div><figcaption>${esc(caption)}<span>${lang==='en'?'Explanatory diagram created for whateveriwant · not a source figure':'whateveriwant 자체 제작 설명 도식 · 원문 이미지 아님'}</span></figcaption></figure>`;
}

Object.assign(configs,{
 'backpropagation':{title:['미분과 갱신의 역할 분리','Separate differentiation from updates'],caption:['역전파는 기울기를 구합니다. 파라미터 갱신은 옵티마이저의 별도 단계입니다.','Backpropagation computes gradients; an optimizer separately updates parameters.'],nodes:row([['예측 계산','Forward pass'],['손실 계산','Compute loss'],['기울기 계산','Backward pass'],['파라미터 갱신','Optimizer step']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'context-retrieval':{title:['검색에서 문맥 구성까지','From retrieval to context'],caption:['후보와 문맥에는 요청자의 접근 권한을 적용합니다. 검색 성공과 답변 정확성은 따로 평가합니다.','Apply access control to retrieval and context. Evaluate retrieval and answer accuracy separately.'],nodes:row([['권한 있는 후보','Authorized candidates'],['재순위화','Rerank'],['문맥 + 출처','Context + sources'],['답변 검증','Verify answer']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-graphs-search':{title:['의존성은 실행 순서를 제한한다','Dependencies constrain execution order'],caption:['정규화 이후의 두 작업은 서로 독립이라는 가정 아래 병렬 실행할 수 있습니다.','The last two tasks may run in parallel if they have no dependency on each other.'],nodes:[n(25,80,['원본 읽기','Read data']),n(255,80,['정규화','Normalize']),n(500,15,['특징 생성','Build features'],'',190),n(500,145,['품질 검사','Check quality'],'',190)],edges:[[0,1],[1,2],[1,3]],height:250}
});

Object.assign(configs,{
 'network-can-bus':{title:['CAN 노드에서 공유 버스까지','From a CAN node to the shared bus'],caption:['한 노드의 구성입니다. 다른 노드도 각자의 트랜시버로 같은 버스에 연결합니다. 배선과 종단은 생략했습니다.','One node and its connection. Other nodes attach through their own transceivers. Wiring and termination are omitted.'],nodes:row([['ECU 애플리케이션','ECU application'],['CAN 컨트롤러','CAN controller'],['트랜시버','Transceiver'],['공유 CAN 버스','Shared CAN bus']]),edges:[[0,1],[1,2],[2,3]]},
 'network-lin':{title:['LIN의 헤더와 응답 순서','LIN header and response order'],caption:['스케줄의 두 슬롯을 단순화했습니다. commander가 헤더를 보내고 해당 프레임의 publisher가 응답합니다. 같은 노드가 두 역할을 맡을 수도 있습니다.','Two simplified schedule slots. The commander sends headers; each designated publisher responds. One node may perform both roles.'],nodes:row([['헤더 A','Header A'],['응답 A','Response A'],['다음 슬롯: 헤더 B','Next slot: header B'],['응답 B','Response B']]),edges:[[0,1],[1,2],[2,3]]},
 'network-layers-packets':{title:['보내는 데이터의 캡슐화','Encapsulation on the sending side'],caption:['각 층은 전달에 필요한 정보를 더합니다. 받는 쪽은 이를 해석하며, 실제 헤더 구조와 중간 장비는 생략했습니다.','Each layer adds delivery information. The receiver interprets it; headers and intermediate devices are simplified.'],nodes:row([['애플리케이션','Application'],['전송 계층','Transport'],['IP 패킷','IP packet'],['링크 프레임','Link frame']]),edges:[[0,1],[1,2],[2,3]]},
 'network-routing-nat':{title:['다음 홉을 따라가는 전달','Forwarding through next hops'],caption:['원격 서버로 갈 때 첫 링크의 목적지는 게이트웨이입니다. 링크 프레임은 홉마다 다시 구성됩니다. NAT 적용 여부는 경로에 따라 다릅니다.','The first link targets the gateway. Link frames are rebuilt at each hop. NAT depends on the path.'],nodes:row([['클라이언트','Client'],['게이트웨이','Gateway'],['중간 라우터','Transit router'],['서버 네트워크','Server network']]),edges:[[0,1],[1,2],[2,3]]},
 'network-dns-dhcp':{title:['리졸버가 필요한 정보를 조회한다','The resolver obtains the needed information'],caption:['캐시에 없을 때의 단순화된 조회 관계입니다. 각 서버는 다음 단계나 최종 정보를 응답하며, 리졸버가 후속 조회를 수행합니다.','Simplified uncached lookup. Servers provide referrals or answers; the resolver makes subsequent queries.'],nodes:[n(15,120,['클라이언트','Client']),n(215,120,['재귀 리졸버','Recursive resolver'],'',175),n(495,15,['루트','Root'],'',200),n(495,125,['상위 도메인','Top-level domain'],'',200),n(495,235,['권한 서버','Authoritative server'],'',200)],edges:[[0,1],[1,2],[1,3],[1,4]],height:330}
});

Object.assign(configs,{
 'vulnerabilities-sql-injection':{title:['쿼리 구조와 값 분리하기','Keep query structure and values separate'],caption:['애플리케이션이 쿼리 구조를 정하고 입력은 값으로 바인딩합니다. 동적 식별자 선택은 별도 허용 목록으로 관리합니다.','The application defines the query; input is bound as a value. Dynamic identifiers need a separate allowlist.'],nodes:[n(25,30,['쿼리 구조','Query structure'],'',180),n(25,155,['입력 값','Input value'],'',180),n(300,95,['매개변수 바인딩','Parameter binding'],'',190),n(560,95,['DB 실행','DB execution'],'',160)],edges:[[0,2],[1,2],[2,3]]},
 'vulnerabilities-access-control':{title:['요청마다 인가 정책 확인','Check authorization for each request'],caption:['주체·대상·행동·조직 경계를 정책으로 판단합니다. 확인되지 않은 요청은 기본 거절하고, 허용된 요청만 처리합니다.','Evaluate subject, object, action and tenant boundaries. Deny by default; process authorized requests only.'],nodes:[n(20,95,['요청','Request'],'',150),n(260,95,['정책 검사','Policy check'],'',190),n(540,30,['허용: 처리','Allow: process'],'',180),n(540,170,['거절','Deny'],'',180)],edges:[[0,1],[1,2],[1,3]]}
});
