import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('.preview',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForSelector('.doc-card');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.doc-card').count(),12);
  await page.screenshot({path:'.preview/desktop.png',fullPage:true});
  await page.locator('#search').fill('LoRA');
  assert.ok(await page.locator('.doc-card').count()>0);
  assert.ok(await page.locator('.doc-card').count()<12);
  await page.locator('#search').fill('검색결과없는단어12345');
  assert.equal(await page.locator('.doc-card').count(),0);
  await page.locator('#search').fill('');
  await page.getByRole('button',{name:'응용',exact:true}).click();
  assert.equal(await page.locator('.doc-card').count(),2);
  await page.getByRole('button',{name:'전체',exact:true}).click();
  await page.locator('.doc-card[href="#/ai/transformer"]').click();
  await page.waitForSelector('.article .katex');
  assert.match(await page.locator('.article blockquote').innerText(),/TL;DR/);
  await page.screenshot({path:'.preview/article.png',fullPage:true});
  await page.reload();
  await page.waitForSelector('.article');
  assert.match(await page.title(),/Transformer/);
  await page.locator('.toc [data-section]').first().click();
  assert.equal(new URL(page.url()).hash,'#/ai/transformer');
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await mobile.goto('http://127.0.0.1:4173/');
  await mobile.waitForSelector('.doc-card');
  await mobile.evaluate(()=>document.fonts.ready);
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await mobile.screenshot({path:'.preview/mobile.png',fullPage:true});
  await mobile.locator('#menu-toggle').click();
  assert.equal(await mobile.locator('#menu-toggle').getAttribute('aria-expanded'),'true');
  await mobile.locator('#quick-links a[href="#/ai/transformer"]').click();
  await mobile.waitForSelector('.article');
  assert.equal(await mobile.locator('#menu-toggle').getAttribute('aria-expanded'),'false');
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  console.log('PASS: 12 documents, search, empty state, filters, article, TL;DR, math, reload, table of contents, mobile navigation and overflow.');
} finally {await browser.close();}
