import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('.preview',{recursive:true});
const catalog=JSON.parse(await fs.readFile('content/catalog.json','utf8'));
const baseURL=new URL(process.argv[2]||'http://127.0.0.1:4173/').href;
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(baseURL);
  await page.waitForSelector('.doc-card');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.doc-card').count(),catalog.length);
  await page.screenshot({path:'.preview/desktop.png',fullPage:true});
  await page.locator('#search').fill('LoRA');
  assert.ok(await page.locator('.doc-card').count()>0);
  assert.ok(await page.locator('.doc-card').count()<catalog.length);
  await page.locator('#search').fill('검색결과없는단어12345');
  assert.equal(await page.locator('.doc-card').count(),0);
  await page.locator('#search').fill('');
  await page.getByRole('button',{name:'응용',exact:true}).click();
  assert.equal(await page.locator('.doc-card').count(),2);
  await page.getByRole('button',{name:'전체',exact:true}).click();
  await page.locator('.track-tabs a[href="#/ml"]').click();
  await page.waitForFunction(()=>document.querySelector('#result-count')?.textContent.includes('6'));
  assert.equal(await page.locator('.doc-card').count(),catalog.filter(d=>d.track==='ml').length);
  await page.reload();
  await page.waitForSelector('.doc-card');
  assert.equal(await page.locator('.doc-card').count(),6);
  await page.locator('.track-tabs a[href="#/dl"]').click();
  await page.waitForSelector('.doc-card[href="#/ai/cnn"]');
  assert.equal(await page.locator('.doc-card').count(),6);
  await page.screenshot({path:'.preview/dl-library.png',fullPage:true});
  await page.locator('.track-tabs a[href="#/ai"]').click();
  await page.locator('.doc-card[href="#/ai/transformer"]').click();
  await page.waitForSelector('.article .katex');
  assert.match(await page.locator('.article blockquote').innerText(),/TL;DR/);
  await page.screenshot({path:'.preview/article.png',fullPage:true});
  await page.reload();
  await page.waitForSelector('.article');
  assert.match(await page.title(),/Transformer/);
  await page.locator('.toc [data-section]').first().click();
  assert.equal(new URL(page.url()).hash,'#/ai/transformer');
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await mobile.goto(baseURL);
  await mobile.waitForSelector('.doc-card');
  await mobile.evaluate(()=>document.fonts.ready);
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await mobile.screenshot({path:'.preview/mobile.png',fullPage:true});
  await mobile.locator('#menu-toggle').click();
  assert.equal(await mobile.locator('#menu-toggle').getAttribute('aria-expanded'),'true');
  await mobile.locator('#quick-links a[href="#/ai/transformer"]').click();
  await mobile.waitForSelector('.article');
  assert.equal(await mobile.locator('#menu-toggle').getAttribute('aria-expanded'),'false');
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const originals=JSON.parse(await fs.readFile('content/en/originals.json','utf8'));
  await page.goto(baseURL+'#/ai/transformer');
  await page.waitForSelector('.concept-diagram svg');
  await page.getByRole('button',{name:'English',exact:true}).click();
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(new URL(page.url()).hash,'#/ai/transformer');
  assert.equal(await page.locator('.original-text .source-paragraph').first().innerText(),originals.concepts.transformer[0].blocks[0].text);
  assert.match(await page.locator('.source-notice').innerText(),/not a translation/);
  await page.screenshot({path:'.preview/english-article.png',fullPage:true});
  await page.reload();
  await page.waitForSelector('.original-text');
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  await page.locator('.article-next a').last().click();
  await page.waitForSelector('.original-text');
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  for(const slug of Object.keys(originals.concepts)){
    await page.goto(baseURL+'#/ai/'+slug);
    await page.waitForSelector('.concept-diagram svg');
    assert.equal(await page.locator('.concept-diagram svg').count(),1);
    assert.equal(await page.locator('.original-text .source-paragraph').first().innerText(),originals.concepts[slug][0].blocks[0].text);
    assert.ok(await page.locator('.attribution a[href="https://creativecommons.org/licenses/by/4.0/"]').count());
  }
  await page.goto(baseURL+'#/');
  await page.waitForSelector('.doc-card');
  await page.locator('#search').fill('경사하강법');
  assert.ok(await page.locator('.doc-card').count()>0);
  await mobile.getByRole('button',{name:'English',exact:true}).click();
  assert.equal(await mobile.locator('html').getAttribute('lang'),'en');
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await mobile.screenshot({path:'.preview/mobile-english.png',fullPage:true});
  await mobile.getByRole('button',{name:'한국어',exact:true}).click();
  assert.match(await mobile.locator('.article blockquote').first().innerText(),/TL;DR/);
  assert.deepEqual(errors,[]);
  console.log('PASS: search, filters, math, navigation; 18 bilingual diagrams, ML/DL categories, verbatim original openings, attribution, language persistence, cross-language search and mobile overflow.');
} finally {await browser.close();}
