const main=document.querySelector('#main');
const sidebar=document.querySelector('#sidebar');
const menu=document.querySelector('#menu-toggle');
let documents=[],filter='전체',query='';
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');});
document.addEventListener('click',event=>{if(!sidebar.contains(event.target)&&!menu.contains(event.target)) closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();if((event.ctrlKey||event.metaKey)&&event.key==='k'){const input=document.querySelector('#search');if(input){event.preventDefault();input.focus();}}});
function closeMenu(){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','메뉴 열기');}
function updateNavigation(slug){document.querySelector('.home-link').classList.toggle('active',!location.hash || location.hash==='#/');document.querySelector('.ai-link').classList.toggle('active',location.hash.startsWith('#/ai'));document.querySelectorAll('#quick-links a').forEach(link=>link.classList.toggle('selected',link.hash==='#/ai/'+slug));}
function card(doc){return `<a class="doc-card" href="#/ai/${doc.slug}"><div class="doc-top"><span class="doc-icon">▧</span> Artificial Intelligence <span class="level">${doc.level}</span></div><h3>${escapeHTML(doc.title)}</h3><p>${escapeHTML(doc.summary)}</p><div class="doc-meta"><span>${doc.minutes}분 읽기 · ${doc.date.replaceAll('-','. ')}</span><span>${doc.slug==='index'?'학습 가이드':doc.slug==='glossary'?'30개 용어':'TL;DR ↗'}</span></div></a>`;}
function showResults(){const grid=document.querySelector('#documents');if(!grid)return;const term=query.toLocaleLowerCase().trim();const matches=documents.filter(doc=>(filter==='전체'||doc.level===filter)&&(!term||doc.source.toLocaleLowerCase().includes(term)||doc.title.toLocaleLowerCase().includes(term)));grid.innerHTML=matches.length?matches.map(card).join(''):'<div class="empty">검색 결과가 없어요. 다른 용어나 필터로 찾아보세요.</div>';document.querySelector('#result-count').textContent=`${matches.length}개의 문서`;document.querySelectorAll('.chip').forEach(button=>{const active=button.dataset.filter===filter;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}
function library(){document.title='whateveriwant — 나만의 지식백과';document.querySelector('#breadcrumb').textContent=location.hash==='#/ai'?'Artificial Intelligence':'지식 라이브러리';main.innerHTML=`<section class="intro"><div class="eyebrow">A SPACE FOR CURIOUS MINDS</div><div class="intro-row"><div><h1>whateveriwant</h1></div><span class="intro-date">첫 컬렉션 · AI 기초와 활용</span></div></section><div class="search-wrap"><span class="search-icon" aria-hidden="true">⌕</span><input type="search" id="search" aria-label="개념과 용어 검색" placeholder="어떤 개념이 궁금한가요?  Transformer, 경사하강법, RAG…" value="${escapeHTML(query)}"><kbd>⌘ K</kbd></div><section class="hero"><div class="hero-copy"><div class="eyebrow">START WITH THE FUNDAMENTALS</div><h2>AI, 처음부터 차근차근.</h2><p>머신러닝의 기본부터 LLM과 RAG까지.<br>10개의 핵심 개념을 따라 AI의 큰 그림을 그려보세요.</p><a href="#/ai/index" class="hero-action">AI 학습 가이드 살펴보기 <span>↗</span></a></div><div class="hero-art" aria-hidden="true"><div class="art-orbit"></div><div class="art-orbit"></div><div class="art-card">01 / FOUNDATION<strong>Machine<br>Learning</strong><i></i><i style="width:70%"></i></div><div class="art-card">02 / CONNECTION<strong>Think.<br>Connect.</strong><i></i><i style="width:65%"></i></div></div></section><div class="section-head"><h2>분야별 둘러보기</h2><span>지식의 범위를 넓혀보세요</span></div><div class="topic-grid"><a class="topic available" href="#/ai"><span class="topic-icon">✳</span><b>Artificial Intelligence</b><small>12개의 문서 ↗</small></a><div class="topic"><span class="topic-icon">◇</span><b>Security</b><small>준비 중</small></div><div class="topic"><span class="topic-icon">⌘</span><b>Computer Science</b><small>준비 중</small></div><div class="topic"><span class="topic-icon">▤</span><b>Operating Systems</b><small>준비 중</small></div><div class="topic"><span class="topic-icon">⛨</span><b>AI for Security</b><small>준비 중</small></div></div><div class="section-head"><h2>${location.hash==='#/ai'?'AI 문서':'지식 라이브러리'}</h2><span>핵심을 먼저, 이해는 더 깊게</span></div><div class="filters" role="group" aria-label="문서 수준 필터">${['전체','기초','핵심','응용','참고','가이드'].map(level=>`<button class="chip" data-filter="${level}" aria-pressed="false">${level}</button>`).join('')}<span class="result-count" id="result-count" aria-live="polite"></span></div><div id="documents" class="document-grid"></div>`;
document.querySelector('#search').addEventListener('input',event=>{query=event.target.value;showResults();});document.querySelectorAll('.chip').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;showResults();}));showResults();}
function article(slug){const doc=documents.find(doc=>doc.slug===slug);if(!doc){main.innerHTML='<div class="empty"><h1>문서를 찾을 수 없어요.</h1><a href="#/">라이브러리로 돌아가기 →</a></div>';document.title='문서 없음 — whateveriwant';document.querySelector('#breadcrumb').textContent='문서 없음';return;}document.title=doc.title+' — whateveriwant';document.querySelector('#breadcrumb').textContent='AI / '+doc.title;const i=documents.indexOf(doc),previous=documents[i-1],next=documents[i+1];main.innerHTML=`<a href="#/ai" class="back-link">← AI 라이브러리</a><div class="reading-layout"><div><header class="article-header"><div class="eyebrow">ARTIFICIAL INTELLIGENCE / ${doc.level}</div><h1>${escapeHTML(doc.title)}</h1><div class="article-meta"><span>${doc.minutes}분 읽기</span><span>출처 확인 ${doc.date}</span><span>AI 작성 해설 · 소유자 검토 전</span></div></header><article class="article">${doc.html}</article><nav class="article-next" aria-label="이전 및 다음 문서">${previous?`<a href="#/ai/${previous.slug}"><small>← 이전 문서</small>${escapeHTML(previous.title)}</a>`:'<span></span>'}${next?`<a href="#/ai/${next.slug}"><small>다음 문서 →</small>${escapeHTML(next.title)}</a>`:''}</nav></div><aside class="toc"><strong>ON THIS PAGE</strong>${doc.headings.map(h=>`<a href="#${h.id}" data-section="${h.id}">${escapeHTML(h.title)}</a>`).join('')}<a class="source-link" href="https://github.com/ttzero25/whateveriwant/blob/main/content/ai/${doc.slug}.md" target="_blank" rel="noopener noreferrer">GitHub에서 문서 보기 ↗</a></aside></div>`;document.querySelectorAll('[data-section]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.getElementById(link.dataset.section)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));}
function route(){closeMenu();const hash=location.hash||'#/';const slug=hash.startsWith('#/ai/')?hash.slice(5):null;updateNavigation(slug);if(slug)article(slug);else library();window.scrollTo(0,0);}
fetch('./documents.json').then(response=>{if(!response.ok)throw new Error('문서를 불러오지 못했습니다.');return response.json();}).then(data=>{documents=data;document.querySelector('#quick-links').innerHTML=['fundamentals','transformer','llm-inference','rag','glossary'].map(slug=>{const doc=documents.find(d=>d.slug===slug);return `<a href="#/ai/${slug}">${escapeHTML(doc.title)}</a>`;}).join('');route();window.addEventListener('hashchange',route);}).catch(()=>{main.innerHTML='<div class="empty"><h1>문서를 불러오지 못했어요.</h1><p>연결 상태를 확인한 뒤 페이지를 새로고침해 주세요.</p><button id="retry">다시 시도</button></div>';document.querySelector('#retry').addEventListener('click',()=>location.reload());});
