import {diagram} from './diagrams.js';
const main=document.querySelector('#main'),sidebar=document.querySelector('#sidebar'),menu=document.querySelector('#menu-toggle');
const E=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let documents=[],filter='전체',query='',lang='ko';
try{lang=localStorage.getItem('whateveriwant-language')==='en'?'en':'ko';}catch{}
const t=(ko,en)=>lang==='en'?en:ko;
const levelNames={'전체':'All','기초':'Foundations','핵심':'Core','응용':'Applied','참고':'Reference','가이드':'Guide'};
const level=value=>lang==='en'?levelNames[value]:value;
const view=doc=>lang==='en'?{...doc,...doc.en}:doc;
function closeMenu(){sidebar.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',t('메뉴 열기','Open menu'));}
menu.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?t('메뉴 닫기','Close menu'):t('메뉴 열기','Open menu'));});
document.addEventListener('click',event=>{if(!sidebar.contains(event.target)&&!menu.contains(event.target))closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();if((event.ctrlKey||event.metaKey)&&event.key==='k'){const input=document.querySelector('#search');if(input){event.preventDefault();input.focus();}}});
function localizeShell(){
 document.documentElement.lang=lang;
 document.querySelector('.brand').setAttribute('aria-label',t('홈','Home'));
 document.querySelector('.home-link').innerHTML=`<span>▦</span> ${t('지식 라이브러리','Knowledge library')} <span class="nav-count">12</span>`;
 document.querySelectorAll('.upcoming small').forEach(el=>el.textContent=t('준비 중','Coming soon'));
 document.querySelector('.sidebar-bottom small').textContent=t('배운 것을, 나의 언어로.','Learn. Connect. Remember.');
 document.querySelector('#quick-links').setAttribute('aria-label',t('AI 문서 바로가기','AI quick links'));
 document.querySelector('#quick-links').innerHTML=['fundamentals','transformer','llm-inference','rag','glossary'].map(slug=>{const d=view(documents.find(d=>d.slug===slug));return `<a href="#/ai/${slug}">${E(d.title)}</a>`;}).join('');
 document.querySelector('footer').innerHTML=`whateveriwant <span>${t('하나씩 배우고, 연결하고, 쌓아가기.','One concept at a time.')}</span><span>${t('공식 자료 기반 · 한국어 해설','Official source excerpts · English')}</span>`;
 document.querySelectorAll('[data-language]').forEach(button=>{const active=button.dataset.language===lang;button.setAttribute('aria-pressed',String(active));button.classList.toggle('active',active);});
}
document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>{if(!documents.length)return;lang=button.dataset.language;try{localStorage.setItem('whateveriwant-language',lang);}catch{}route();}));
function card(original){const doc=view(original);return `<a class="doc-card" href="#/ai/${doc.slug}"><div class="doc-top"><span class="doc-icon">▧</span> Artificial Intelligence <span class="level">${level(doc.level)}</span></div><h3>${E(doc.title)}</h3><p>${E(doc.summary)}</p><div class="doc-meta"><span>${lang==='en'?(original.en.type==='navigation'?'Site guide':'Google · original excerpt'):`${doc.minutes}분 읽기 · ${doc.date.replaceAll('-','. ')}`}</span><span>${doc.slug==='index'?t('학습 가이드','Guide'):doc.slug==='glossary'?t('용어집','Glossary'):'TL;DR ↗'}</span></div></a>`;}
function showResults(){const grid=document.querySelector('#documents');if(!grid)return;const term=query.toLocaleLowerCase().trim();const matches=documents.filter(doc=>(filter==='전체'||doc.level===filter)&&(!term||[doc.source,doc.title,doc.en.source,doc.en.title].join(' ').toLocaleLowerCase().includes(term)));grid.innerHTML=matches.length?matches.map(card).join(''):`<div class="empty">${t('검색 결과가 없어요. 다른 용어나 필터로 찾아보세요.','No results. Try another term or filter.')}</div>`;document.querySelector('#result-count').textContent=t(`${matches.length}개의 문서`,`${matches.length} documents`);document.querySelectorAll('.chip').forEach(button=>{const active=button.dataset.filter===filter;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}
function library(){
 document.title='whateveriwant — '+t('나만의 지식백과','Personal knowledge base');document.querySelector('#breadcrumb').textContent=location.hash==='#/ai'?'Artificial Intelligence':t('지식 라이브러리','Knowledge library');
 main.innerHTML=`<section class="intro"><div class="eyebrow">A SPACE FOR CURIOUS MINDS</div><div class="intro-row"><div><h1>whateveriwant</h1></div><span class="intro-date">${t('첫 컬렉션 · AI 기초와 활용','FIRST COLLECTION · AI FOUNDATIONS & APPLICATIONS')}</span></div></section><div class="search-wrap"><span class="search-icon" aria-hidden="true">⌕</span><input type="search" id="search" aria-label="${t('개념과 용어 검색','Search concepts and terms')}" placeholder="${t('어떤 개념이 궁금한가요?  Transformer, 경사하강법, RAG…','Search concepts in Korean or English…')}" value="${E(query)}"><kbd>⌘ K</kbd></div><div class="section-head"><h2>${t('분야별 둘러보기','Explore topics')}</h2><span>${t('지식의 범위를 넓혀보세요','Connect ideas across disciplines')}</span></div><div class="topic-grid"><a class="topic available" href="#/ai"><span class="topic-icon">✳</span><b>Artificial Intelligence</b><small>${t('12개의 문서','12 documents')} ↗</small></a>${[['◇','Security'],['⌘','Computer Science'],['▤','Operating Systems'],['⛨','AI for Security']].map(([icon,title])=>`<div class="topic"><span class="topic-icon">${icon}</span><b>${title}</b><small>${t('준비 중','Coming soon')}</small></div>`).join('')}</div><div class="section-head"><h2>${location.hash==='#/ai'?t('AI 문서','AI documents'):t('지식 라이브러리','Knowledge library')}</h2><span>${t('핵심을 먼저, 이해는 더 깊게','Start with the essentials')}</span></div><div class="filters" role="group" aria-label="${t('문서 수준 필터','Filter by level')}">${Object.keys(levelNames).map(l=>`<button class="chip" data-filter="${l}" aria-pressed="false">${level(l)}</button>`).join('')}<span class="result-count" id="result-count" aria-live="polite"></span></div><div id="documents" class="document-grid"></div>`;
 document.querySelector('#search').addEventListener('input',event=>{query=event.target.value;showResults();});document.querySelectorAll('.chip').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;showResults();}));showResults();
}
function article(slug){
 const original=documents.find(d=>d.slug===slug);if(!original){main.innerHTML=`<div class="empty"><h1>${t('문서를 찾을 수 없어요.','Document not found.')}</h1><a href="#/">${t('라이브러리로 돌아가기','Back to library')} →</a></div>`;document.title=t('문서 없음','Not found')+' — whateveriwant';document.querySelector('#breadcrumb').textContent=t('문서 없음','Not found');return;}
 const doc=view(original);document.title=doc.title+' — whateveriwant';document.querySelector('#breadcrumb').textContent='AI / '+doc.title;
 const i=documents.indexOf(original),previous=documents[i-1],next=documents[i+1];
 const figure=diagram(slug,lang);
 const notice=lang==='en'&&doc.type==='original'?`<div class="source-notice"><strong>Original English · selected excerpts</strong><p>Google’s original wording, not a translation of the Korean article. The excerpts cover related concepts; source figures and later paragraphs are available through the original links.</p></div>`:'';
 let body=doc.html;
 // Keep TL;DR first, then place the explanatory diagram before the source sections.
 if(figure)body=body.replace('</blockquote>','</blockquote>'+figure);
 const meta=lang==='en'?(doc.type==='navigation'?'Site navigation · authored for whateveriwant':'Google · CC BY 4.0 · original excerpts'):'AI 작성 해설 · 소유자 검토 전';
 main.innerHTML=`<a href="#/ai" class="back-link">← ${t('AI 라이브러리','AI library')}</a><div class="reading-layout"><div><header class="article-header"><div class="eyebrow">ARTIFICIAL INTELLIGENCE / ${level(doc.level)}</div><h1>${E(doc.title)}</h1><div class="article-meta">${lang==='ko'?`<span>${doc.minutes}분 읽기</span>`:''}<span>${t('출처 확인','Source checked')} ${doc.date}</span><span>${meta}</span></div></header>${notice}<article class="article">${body}</article><nav class="article-next" aria-label="${t('이전 및 다음 문서','Previous and next articles')}">${previous?`<a href="#/ai/${previous.slug}"><small>← ${t('이전 문서','Previous')}</small>${E(view(previous).title)}</a>`:'<span></span>'}${next?`<a href="#/ai/${next.slug}"><small>${t('다음 문서','Next')} →</small>${E(view(next).title)}</a>`:''}</nav></div><aside class="toc"><strong>ON THIS PAGE</strong>${doc.headings.map(h=>`<a href="#${h.id}" data-section="${h.id}">${E(h.title)}</a>`).join('')}<a class="source-link" href="https://github.com/ttzero25/whateveriwant/blob/main/content/${lang==='en'?'en/originals.json':'ai/'+doc.slug+'.md'}" target="_blank" rel="noopener noreferrer">${t('GitHub에서 문서 보기','View on GitHub')} ↗</a></aside></div>`;
 document.querySelectorAll('[data-section]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.getElementById(link.dataset.section)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));
}
function route(){localizeShell();closeMenu();const hash=location.hash||'#/',slug=hash.startsWith('#/ai/')?hash.slice(5):null;document.querySelector('.home-link').classList.toggle('active',hash==='#/');document.querySelector('.ai-link').classList.toggle('active',hash.startsWith('#/ai'));document.querySelectorAll('#quick-links a').forEach(a=>a.classList.toggle('selected',a.hash==='#/ai/'+slug));if(slug)article(slug);else library();window.scrollTo(0,0);}
fetch('./documents.json').then(r=>{if(!r.ok)throw Error('Load failed');return r.json();}).then(data=>{documents=data;route();window.addEventListener('hashchange',route);}).catch(()=>{main.innerHTML=`<div class="empty"><h1>${t('문서를 불러오지 못했어요.','Unable to load documents.')}</h1><button id="retry">${t('다시 시도','Retry')}</button></div>`;document.querySelector('#retry').addEventListener('click',()=>location.reload());});
