const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(value,lang)=>Array.isArray(value)?value[lang==='en'?1:0]:value;
const n=(x,y,label,sub='',w=145)=>({x,y,label,sub,w});
const row=(labels)=>labels.map((label,i)=>n(22+i*178,80,label));
const configs={
 fundamentals:{title:['AI 안에서 ML, 그 안에서 딥러닝','AI contains ML; ML contains deep learning'],caption:['개념의 포함 관계를 단순화한 도식입니다. 모든 AI가 머신러닝이나 LLM인 것은 아닙니다.','A simplified hierarchy. Not every AI system is machine learning or an LLM.'],kind:'hierarchy'},
 'data-and-generalization':{title:['데이터를 나누는 세 가지 목적','Three roles for dataset splits'],caption:['분할 비율을 나타내는 그림이 아닙니다. 테스트 데이터는 모델 선택이 끝날 때까지 분리해 둡니다.','Box sizes do not represent split ratios. Keep test data separate until model selection is complete.'],nodes:[n(288,15,['데이터셋','Dataset']),n(30,115,['학습 세트','Training set'],['가중치 갱신','Update weights'],190),n(265,115,['검증 세트','Validation set'],['모델·설정 선택','Select model & settings'],190),n(500,115,['테스트 세트','Test set'],['최종 평가','Final evaluation'],190)],edges:[[0,1],[0,2],[0,3]]},
 training:{title:['학습의 반복 과정','The training loop'],caption:['역전파는 기울기를 계산하고, 옵티마이저는 가중치를 갱신합니다. 갱신한 모델로 다음 배치를 처리합니다.','Backpropagation computes gradients; the optimizer updates weights before the next batch.'],nodes:row([['순전파','Forward pass'],['손실 계산','Compute loss'],['역전파','Backpropagation'],['가중치 갱신','Update weights']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'neural-networks':{title:['층을 통과하며 변하는 표현','Representations across layers'],caption:['완전연결 신경망의 예시입니다. 원은 뉴런, 선은 학습되는 연결을 나타냅니다.','An example of a fully connected network. Circles are neurons; lines represent learned connections.'],kind:'network'},
 evaluation:{title:['무엇을 맞히고, 무엇을 놓쳤을까?','What was detected, and what was missed?'],caption:['양성은 찾으려는 대상입니다. 정밀도는 TP/(TP+FP), 재현율은 TP/(TP+FN)입니다.','Positive means the target class. Precision = TP/(TP+FP); recall = TP/(TP+FN).'],kind:'matrix'},
 'tokens-and-embeddings':{title:['텍스트에서 벡터까지','From text to vectors'],caption:['토큰 분할과 ID는 토크나이저에 따라 달라집니다. ID의 크기가 의미적 유사도를 나타내지는 않습니다.','Token boundaries and IDs depend on the tokenizer. ID magnitude does not indicate semantic similarity.'],nodes:row([['텍스트','Text'],['토큰화','Tokenization'],['토큰 ID','Token IDs'],['임베딩 벡터','Embedding vectors']]),edges:[[0,1],[1,2],[2,3]]},
 transformer:{title:['Attention의 정보 흐름','Information flow in attention'],caption:['Q와 K로 관계 점수를 계산하고, softmax 가중치로 V를 결합합니다. 위치별·헤드별 계산은 생략했습니다.','Q and K produce scores; softmax weights combine V. Per-position and per-head details are omitted.'],nodes:[n(20,25,'Q'),n(20,140,'K'),n(220,80,['관계 점수','QKᵀ / √dₖ']),n(420,80,'softmax'),n(420,195,'V'),n(610,80,['가중합','Weighted sum'],'',130)],edges:[[0,2],[1,2],[2,3],[3,5],[4,5]],height:300},
 'llm-inference':{title:['다음 토큰을 하나씩 이어 쓰기','Generate one token at a time'],caption:['선택한 토큰을 문맥에 붙이고 반복합니다. 종료 토큰이나 길이 제한에 도달하면 멈춥니다.','Append the selected token to the context and repeat until a stop token or length limit.'],nodes:row([['현재 문맥','Current context'],['모델 계산','Model forward pass'],['다음 토큰 선택','Select next token'],['문맥에 추가','Append to context']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 rag:{title:['검색 자료를 근거로 답변하기','Ground answers in retrieved sources'],caption:['문서 색인은 검색에 쓰이고, 검색 결과는 질문과 함께 모델에 전달됩니다. 모델 가중치를 갱신하는 과정은 아닙니다.','The index supports retrieval. Retrieved passages and the question enter the model; weights are not updated.'],nodes:[n(25,15,['문서 색인','Document index']),n(25,130,['질문','Question']),n(220,75,['관련 문서 검색','Retrieve passages']),n(415,75,['질문 + 근거','Question + context']),n(610,75,['모델 답변','Model answer'],'',130)],edges:[[0,2],[1,2],[2,3],[1,3],[3,4]],height:235},
 'fine-tuning':{title:['LoRA: 원본 가중치와 작은 변화량','LoRA: base weights plus a small update'],caption:['기본 가중치 W를 고정하고 A·B를 학습합니다. 실제 구현의 스케일 계수는 생략한 구조도입니다.','Freeze W and train A and B. This structural diagram omits the implementation’s scaling factor.'],nodes:[n(25,90,['입력 x','Input x']),n(240,25,['기본 가중치 W','Frozen weights W'],['고정','Frozen'],195),n(230,155,'A',['학습','Trainable'],105),n(380,155,'B',['학습','Trainable'],105),n(570,90,['Wx + BAx','Wx + BAx'],['출력','Output'],160)],edges:[[0,1],[0,2],[2,3],[1,4],[3,4]],height:270}
};
function body(config,lang){
 if(config.kind==='hierarchy')return `<rect x="35" y="20" width="675" height="215" rx="16" fill="#eaf1ec" stroke="#b8ccbe"/><text x="60" y="55">AI · ${lang==='en'?'Artificial Intelligence':'인공지능'}</text><rect x="185" y="75" width="495" height="135" rx="13" fill="#dce9df" stroke="#aec4b4"/><text x="210" y="106">ML · ${lang==='en'?'Machine Learning':'머신러닝'}</text><rect x="360" y="128" width="290" height="58" rx="10" fill="#52745e"/><text x="505" y="162" text-anchor="middle" fill="white">${lang==='en'?'Deep Learning':'딥러닝'}</text>`;
 if(config.kind==='network'){
  const layers=[[65,[85,155]],[270,[50,120,190]],[480,[85,155]],[670,[120]]];let out='';
  for(let i=0;i<layers.length-1;i++)for(const y of layers[i][1])for(const yy of layers[i+1][1])out+=`<line x1="${layers[i][0]}" y1="${y}" x2="${layers[i+1][0]}" y2="${yy}" stroke="#c2d3c8"/>`;
  layers.forEach(([x,ys],i)=>{ys.forEach(y=>out+=`<circle cx="${x}" cy="${y}" r="17" fill="${i===3?'#587963':'#e3eee6'}" stroke="#91b29b"/>`);out+=`<text x="${x}" y="235" text-anchor="middle">${pick([['입력','Input'],['은닉층 1','Hidden 1'],['은닉층 2','Hidden 2'],['출력','Output']][i],lang)}</text>`;});return out;
 }
 if(config.kind==='matrix'){
  let out=`<text x="315" y="28" text-anchor="middle">${lang==='en'?'Predicted positive':'양성 예측'}</text><text x="560" y="28" text-anchor="middle">${lang==='en'?'Predicted negative':'음성 예측'}</text>`;
  [[65,'TP',['올바른 탐지','Correct detection'],'#e2eee5'],[155,'FP',['오탐','False alarm'],'#f5eee3']].forEach(([y,key,label,fill],i)=>{out+=`<text x="95" y="${y+40}" text-anchor="middle">${lang==='en'?(i?'Actual negative':'Actual positive'):(i?'실제 음성':'실제 양성')}</text>`;out+=`<rect x="195" y="${y}" width="230" height="75" rx="8" fill="${fill}"/><text x="310" y="${y+30}" text-anchor="middle">${key}</text><text class="diagram-sub" x="310" y="${y+55}" text-anchor="middle">${pick(label,lang)}</text>`;const label2=i?['올바른 제외','Correct rejection']:['미탐','Missed detection'];out+=`<rect x="440" y="${y}" width="230" height="75" rx="8" fill="${i?'#e2eee5':'#f5eee3'}"/><text x="555" y="${y+30}" text-anchor="middle">${i?'TN':'FN'}</text><text class="diagram-sub" x="555" y="${y+55}" text-anchor="middle">${pick(label2,lang)}</text>`;});return out;
 }
 let out='';
 for(const [from,to]of config.edges){const a=config.nodes[from],b=config.nodes[to];const horizontal=Math.abs(b.x-a.x)>100;const x1=horizontal?a.x+a.w:a.x+a.w/2,y1=horizontal?a.y+30:a.y+60,x2=horizontal?b.x:b.x+b.w/2,y2=horizontal?b.y+30:b.y;out+=`<path d="M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2-4} ${y2}" fill="none" stroke="#9bb5a3" stroke-width="1.6" marker-end="url(#arrow)"/>`;}
 if(config.loop)out+='<path d="M 630 143 V 195 H 94 V 146" fill="none" stroke="#9bb5a3" stroke-width="1.5" stroke-dasharray="5 4" marker-end="url(#arrow)"/>';
 for(const node of config.nodes){const label=pick(node.label,lang),sub=pick(node.sub,lang);out+=`<rect x="${node.x}" y="${node.y}" width="${node.w}" height="60" rx="10" fill="#edf4ef" stroke="#c5d7cb"/><text x="${node.x+node.w/2}" y="${node.y+(sub?26:35)}" text-anchor="middle">${esc(label)}</text>${sub?`<text class="diagram-sub" x="${node.x+node.w/2}" y="${node.y+46}" text-anchor="middle">${esc(sub)}</text>`:''}`;}
 return out;
}
export function diagram(slug,lang){const c=configs[slug];if(!c)return '';const title=pick(c.title,lang),caption=pick(c.caption,lang),height=c.height||260;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 ${height}" role="img" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">${esc(title)}</title><desc id="diagram-desc">${esc(caption)}</desc><style>text{font:14px system-ui,sans-serif;fill:#496852}.diagram-sub{font-size:11px;fill:#71877a}text[fill="white"]{fill:white}</style><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#9bb5a3"/></marker></defs>${body(c,lang)}</svg>`;
 return `<figure class="concept-diagram"><div class="diagram-heading"><strong>${esc(title)}</strong><a download="${slug}-${lang}.svg" href="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}">SVG ↓</a></div><div class="diagram-scroll">${svg}</div><figcaption>${esc(caption)}<span>${lang==='en'?'Explanatory diagram created for whateveriwant · not a source figure':'whateveriwant 자체 제작 설명 도식 · 원문 이미지 아님'}</span></figcaption></figure>`;
}
