const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(value,lang)=>Array.isArray(value)?value[lang==='en'?1:0]:value;
const n=(x,y,label,sub='',w=145)=>({x,y,label,sub,w});
const row=(labels)=>labels.map((label,i)=>n(22+i*178,80,label));
const configs={
 fundamentals:{title:['AI 안에서 ML, 그 안에서 딥러닝','AI contains ML; ML contains deep learning'],caption:['개념의 포함 관계를 단순화한 도식입니다. 모든 AI가 머신러닝이나 LLM인 것은 아닙니다.','A simplified hierarchy. Not every AI system is machine learning or an LLM.'],kind:'hierarchy'},
 'data-and-generalization':{title:['데이터를 나누는 세 가지 목적','Three roles for dataset splits'],caption:['분할 비율을 나타내는 그림이 아닙니다. 테스트 데이터는 모델 선택이 끝날 때까지 분리해 둡니다.','Box sizes do not represent split ratios. Keep test data separate until model selection is complete.'],nodes:[n(288,15,['데이터셋','Dataset']),n(30,115,['학습 세트','Training set'],['가중치 갱신','Update weights'],190),n(265,115,['검증 세트','Validation set'],['모델·설정 선택','Select model & settings'],190),n(500,115,['테스트 세트','Test set'],['최종 평가','Final evaluation'],190)],edges:[[0,1],[0,2],[0,3]]},
 training:{title:['학습의 반복 과정','The training loop'],caption:['역전파는 기울기를 계산하고, 옵티마이저는 가중치를 갱신합니다. 갱신한 모델로 다음 배치를 처리합니다.','Backpropagation computes gradients; the optimizer updates weights before the next batch.'],nodes:row([['순전파','Forward pass'],['손실 계산','Compute loss'],['역전파','Backpropagation'],['가중치 갱신','Update weights']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'neural-networks':{title:['층을 통과하며 변하는 표현','Representations across layers'],caption:['완전연결 신경망의 예시입니다. 원은 뉴런, 선은 학습되는 연결을 나타냅니다.','An example of a fully connected network. Circles are neurons; lines represent learned connections.'],kind:'network'},
 evaluation:{title:['무엇을 맞히고, 무엇을 놓쳤을까?','What was detected, and what was missed?'],caption:['양성은 찾으려는 대상입니다. 정밀도는 TP/(TP+FP), 재현율은 TP/(TP+FN)입니다.','Positive means the target class. Precision = TP/(TP+FP); recall = TP/(TP+FN).'],kind:'matrix'},
 'tokens-and-embeddings':{title:['텍스트에서 벡터까지','From text to vectors'],caption:['토큰 분할과 ID는 토크나이저에 따라 달라집니다. ID의 크기가 의미적 유사도를 나타내지는 않습니다.','Token boundaries and IDs depend on the tokenizer. ID magnitude does not indicate semantic similarity.'],nodes:row([['텍스트','Text'],['토큰화','Tokenization'],['토큰 ID','Token IDs'],['임베딩 벡터','Embedding vectors']]),edges:[[0,1],[1,2],[2,3]]},
 transformer:{title:['Attention의 정보 흐름','Information flow in attention'],caption:['Q와 K로 관계 점수를 계산하고, softmax 가중치로 V를 결합합니다. 위치별·헤드별 계산은 생략했습니다.','Q and K produce scores; softmax weights combine V. Per-position and per-head details are omitted.'],nodes:[n(20,25,'Q'),n(20,140,'K'),n(220,80,['관계 점수','QKᵀ / √dₖ']),n(420,80,'softmax'),n(420,195,'V'),n(610,80,['가중합','Weighted sum'],'',130)],edges:[[0,2],[1,2],[2,3],[3,5],[4,5]],height:300},
 'llm-inference':{title:['다음 토큰을 하나씩 이어 쓰기','Generate one token at a time'],caption:['선택한 토큰을 문맥에 붙이고 반복합니다. 종료 토큰이나 길이 제한에 도달하면 멈춥니다.','Append the selected token to the context and repeat until a stop token or length limit.'],nodes:row([['현재 문맥','Current context'],['모델 계산','Model forward pass'],['다음 토큰 선택','Select next token'],['문맥에 추가','Append to context']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 rag:{title:['검색 자료를 근거로 답변하기','Ground answers in retrieved sources'],caption:['문서 색인은 검색에 쓰이고, 검색 결과는 질문과 함께 모델에 전달됩니다. 모델 가중치를 갱신하는 과정은 아닙니다.','The index supports retrieval. Retrieved passages and the question enter the model; weights are not updated.'],nodes:[n(25,15,['문서 색인','Document index']),n(25,130,['질문','Question']),n(220,75,['관련 문서 검색','Retrieve passages']),n(415,75,['질문 + 근거','Question + context']),n(610,75,['모델 답변','Model answer'],'',130)],edges:[[0,2],[1,2],[2,3],[1,3],[3,4]],height:235},
 'fine-tuning':{title:['LoRA: 원본 가중치와 작은 변화량','LoRA: base weights plus a small update'],caption:['기본 가중치 W를 고정하고 A·B를 학습합니다. 실제 구현의 스케일 계수는 생략한 구조도입니다.','Freeze W and train A and B. This structural diagram omits the implementation’s scaling factor.'],nodes:[n(25,90,['입력 x','Input x']),n(240,25,['기본 가중치 W','Frozen weights W'],['고정','Frozen'],195),n(230,155,'A',['학습','Trainable'],105),n(380,155,'B',['학습','Trainable'],105),n(570,90,['Wx + BAx','Wx + BAx'],['출력','Output'],160)],edges:[[0,1],[0,2],[2,3],[1,4],[3,4]],height:270}
};
Object.assign(configs,{
 'linear-regression':{title:['특성의 가중합으로 수치 예측','Predict a number from weighted features'],caption:['입력 특성에 학습한 가중치를 곱하고 편향을 더합니다. 예측과 실제 값의 차이를 손실로 측정합니다.','Multiply features by learned weights, add bias, and compare the prediction with the target.'],nodes:row([['입력 특성 x','Input features x'],['가중합 wᵀx + b','Weighted sum'],['수치 예측 ŷ','Prediction ŷ'],['실제 값과 비교','Compare with target']]),edges:[[0,1],[1,2],[2,3]]},
 'logistic-regression':{title:['확률 추정과 최종 판정 구분하기','Separate probability from the decision'],caption:['Sigmoid는 선형 점수를 0~1로 바꿉니다. 임계값은 확률 추정 이후에 적용하는 별도 선택입니다.','Sigmoid maps a linear score to (0,1). The decision threshold is a separate choice.'],nodes:row([['선형 점수 z','Linear score z'],['Sigmoid','Sigmoid'],['확률 추정 p','Estimated p'],['임계값으로 판정','Apply threshold']]),edges:[[0,1],[1,2],[2,3]]},
 'decision-trees':{title:['질문과 답을 따라 리프로 이동','Follow conditions to a leaf'],caption:['배송 예측을 설명하는 가상 규칙입니다. 실제 트리 학습은 데이터로 분기 조건을 선택합니다.','Illustrative delivery rules, not a trained model. Training selects splits from data.'],nodes:[n(285,10,['거리 ≤ 10km?','Distance ≤ 10km?'],'',180),n(95,105,['물량 ≤ 100?','Volume ≤ 100?'],['예 / Yes','Yes'],180),n(510,105,['느림','Slow'],['아니오 / No','No'],150),n(25,205,['빠름','Fast'],['예 / Yes','Yes'],140),n(245,205,['보통','Normal'],['아니오 / No','No'],140)],edges:[[0,1],[0,2],[1,3],[1,4]],height:290},
 clustering:{title:['K-means의 반복','The K-means loop'],caption:['K를 정하고 중심점에 배정한 뒤 평균으로 중심을 갱신합니다. 초기화와 특성 스케일에 따라 결과가 달라집니다.','Choose K, assign points, and update means. Initialization and feature scaling affect the result.'],nodes:row([['K·초기 중심 선택','Choose K & centers'],['가까운 중심에 배정','Assign nearest'],['군집 평균 계산','Compute means'],['중심 갱신·반복','Update & repeat']]),edges:[[0,1],[1,2],[2,3]]},
 'activation-functions':{title:['ReLU를 통과하는 값','Values passing through ReLU'],caption:['ReLU(x)=max(0,x). 음수는 0이 되고 양수는 유지됩니다. 다른 활성화 함수는 다른 변환을 사용합니다.','ReLU(x)=max(0,x). Negative values become zero; positive values pass through.'],nodes:[n(45,85,'[-2, 0, 3]',['입력','Input'],190),n(285,85,'ReLU',['max(0, x)','max(0, x)'],190),n(525,85,'[0, 0, 3]',['출력','Output'],190)],edges:[[0,1],[1,2]]},
 cnn:{title:['CNN에서 공간 크기와 채널 변화','Spatial size and channels in a CNN'],caption:['예시: 3×3 필터 16개, stride 1, valid padding. 배치 축은 생략했습니다.','Example: 16 filters of size 3×3, stride 1, valid padding. The batch axis is omitted.'],nodes:row([['32 × 32 × 3','32 × 32 × 3'],['Conv 3×3 / 16','Conv 3×3 / 16'],['30 × 30 × 16','30 × 30 × 16'],['ReLU','ReLU']]),edges:[[0,1],[1,2],[2,3]]},
 rnn:{title:['같은 셀, 시간에 따라 바뀌는 상태','Shared cell, evolving hidden state'],caption:['모든 시간 단계에서 가중치를 공유합니다. 현재 입력과 이전 상태를 함께 사용해 다음 상태를 만듭니다.','Weights are shared across time. Each step combines its input with the previous state.'],nodes:[n(25,90,'h₀'),n(215,90,'RNN → h₁'),n(405,90,'RNN → h₂'),n(595,90,'RNN → h₃'),n(215,190,'x₁'),n(405,190,'x₂'),n(595,190,'x₃')],edges:[[0,1],[1,2],[2,3],[4,1],[5,2],[6,3]],height:275},
 regularization:{title:['데이터 손실에 가중치 페널티 더하기','Add a weight penalty to data loss'],caption:['L2 정규화의 예시입니다. λ는 검증 데이터로 조절하며, dropout이나 조기 종료와는 다른 기법입니다.','L2 example. Tune λ on validation data; dropout and early stopping are different techniques.'],nodes:[n(45,30,['데이터 손실','Data loss'],'L data',180),n(45,140,['가중치 페널티','Weight penalty'],'λ Σ w²',180),n(310,85,['합산','Sum'],'L total',170),n(545,85,['최적화','Optimize'],['가중치 갱신','Update weights'],170)],edges:[[0,2],[1,2],[2,3]]}
});
Object.assign(configs,{
 'cs-data-representation':{title:['문자가 바이트로 저장되는 과정','Encoding a character as a byte'],caption:['문자 A의 UTF-8 바이트는 01000001입니다. 같은 비트열을 부호 없는 정수로 읽으면 65입니다. 해석 규칙에 따라 의미가 달라집니다.','The UTF-8 byte for A is 01000001. Interpreted as an unsigned integer, these bits mean 65. Meaning depends on interpretation.'],nodes:row([['문자 A','Character A'],['UTF-8 인코딩','UTF-8 encoding'],'01000001',['정수로 읽으면 65','As an integer: 65']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-computer-architecture':{title:['저장장치에서 CPU까지','From storage to CPU'],caption:['필요한 데이터를 메모리로 가져와 사용하는 흐름을 단순화했습니다. 캐시에 있는 데이터는 RAM을 다시 읽지 않아도 됩니다.','A simplified path for loading and using data. A cache hit avoids another RAM access.'],nodes:row([['저장장치','Storage'],['RAM','RAM'],['캐시','Cache'],['CPU · 레지스터','CPU · registers']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-data-structures':{title:['스택과 큐의 꺼내는 순서','Stack and queue removal order'],caption:['A, B, C 순서로 넣었습니다. 스택은 마지막 항목부터, 큐는 첫 항목부터 꺼냅니다.','Insert A, B, C in that order. A stack removes the last item first; a queue removes the first item first.'],nodes:[n(30,90,'A → B → C'),n(280,25,['스택 · LIFO','Stack · LIFO']),n(280,150,['큐 · FIFO','Queue · FIFO']),n(550,25,'C → B → A'),n(550,150,'A → B → C')],edges:[[0,1],[0,2],[1,3],[2,4]]},
 'algorithms-algorithms-complexity':{title:['이진 탐색은 후보를 반씩 줄입니다','Binary search halves the candidates'],caption:['정렬된 데이터에서 한 번 비교할 때마다 남은 탐색 범위를 대략 절반으로 줄입니다. 마지막 화살표는 여러 비교를 생략한 것입니다.','In sorted data, each comparison roughly halves the remaining range. The final arrow omits several comparisons.'],nodes:row(['1,024','512','256',['… → 1','… → 1']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-networking':{title:['웹 요청의 큰 흐름','A simplified web request'],caption:['주소 확인, 연결, 요청, 응답의 개념도입니다. 캐시·연결 재사용·TLS 협상과 HTTP 버전별 세부 차이는 생략했습니다.','Address resolution, connection, request and response. Caches, connection reuse, TLS negotiation and HTTP version differences are omitted.'],nodes:row([['DNS 주소 확인','DNS lookup'],['서버 연결','Connect to server'],['HTTP 요청','HTTP request'],['HTTP 응답','HTTP response']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-databases':{title:['키로 두 테이블 연결하기','Join two tables using keys'],caption:['users.id와 orders.user_id가 같은 행을 연결하는 예시입니다. 한 사용자가 여러 주문을 가지면 결과에도 여러 행이 생깁니다.','Match users.id to orders.user_id. A user with multiple matching orders appears in multiple result rows.'],nodes:[n(25,25,'users','id · name',185),n(25,150,'orders','user_id · item',185),n(300,85,'JOIN','id = user_id',180),n(550,85,['결과 행','Result rows'],'name · item',180)],edges:[[0,2],[1,2],[2,3]]},
 'cs-transactions-indexes':{title:['여러 변경을 하나로 확정하기','Commit multiple changes together'],caption:['송금의 차감과 입금을 하나의 트랜잭션으로 묶습니다. 모두 성공하면 COMMIT하고, 실패하면 ROLLBACK으로 변경을 취소합니다.','Group debit and credit in one transaction. COMMIT on success; ROLLBACK discards the changes on failure.'],nodes:row(['BEGIN',['계좌 A 차감','Debit account A'],['계좌 B 입금','Credit account B'],'COMMIT']),edges:[[0,1],[1,2],[2,3]]},
 'cs-concurrency':{title:['갱신 하나가 사라지는 경쟁 상태','A lost update'],caption:['초기 값은 0입니다. 두 작업이 각자 1을 더하지만, 읽기와 쓰기가 원자적이지 않아 최종 값이 기대한 2 대신 1이 됩니다.','Start at 0. Two tasks each add 1, but non-atomic read–modify–write operations leave 1 instead of the expected 2.'],nodes:row([['A: 0 읽기','A: read 0'],['B: 0 읽기','B: read 0'],['A: 1 쓰기','A: write 1'],['B: 1 쓰기','B: write 1']]),edges:[[0,1],[1,2],[2,3]]}
});
Object.assign(configs,{
 'os-kernel-system-calls':{title:['프로그램이 커널에 서비스를 요청하기','Requesting a kernel service'],caption:['필요한 시스템 콜을 수행하는 흐름입니다. 라이브러리 내부에서 처리되는 호출은 커널에 들어가지 않을 수 있으며, 모드 전환이 반드시 스레드 교체를 뜻하지는 않습니다.','A call requiring kernel service. Some library calls stay in user mode; a mode transition does not necessarily switch threads.'],nodes:row([['프로그램','Application'],['라이브러리','Library'],['시스템 콜 · 커널','System call · kernel'],['결과 반환','Return result']]),edges:[[0,1],[1,2],[2,3]]},
 'os-processes-threads':{title:['I/O를 기다렸다가 다시 실행하기','Waiting for I/O and becoming ready'],caption:['준비 → 실행 → I/O 대기 → 준비의 단순화한 흐름입니다. 대기가 끝나도 CPU를 다시 배정받아야 실행됩니다. 선점·종료 등의 전이는 생략했습니다.','Ready → running → waiting for I/O → ready. Becoming ready still requires scheduling. Preemption and exit transitions are omitted.'],nodes:row([['준비','Ready'],['실행','Running'],['I/O 대기','Blocked on I/O'],['다시 준비','Ready again']]),edges:[[0,1],[1,2],[2,3]]},
 'os-cpu-scheduling':{title:['시간을 나누어 번갈아 실행하기','Round-robin time sharing'],caption:['A와 B가 각각 CPU 4ms를 필요로 하고 시간 할당량은 2ms인 예시입니다. 전환 비용과 I/O는 생략했습니다.','A and B each need 4 ms of CPU time with a 2 ms quantum. Context-switch overhead and I/O are omitted.'],nodes:row(['A · 0–2 ms','B · 2–4 ms','A · 4–6 ms','B · 6–8 ms']),edges:[[0,1],[1,2],[2,3]]},
 'os-virtual-memory':{title:['가상 페이지를 물리 프레임으로 연결','Mapping a virtual page to a physical frame'],caption:['페이지 크기 4,096바이트, 가상 페이지 2 → 물리 프레임 7인 예시입니다. 오프셋 8은 유지되어 물리 주소는 28,680입니다. TLB와 다단계 조회는 생략했습니다.','Example: 4,096-byte pages, virtual page 2 mapped to frame 7. Offset 8 is preserved, giving physical address 28,680. TLB and multilevel lookup are omitted.'],nodes:row([['가상 주소 8,200','Virtual: 8,200'],['페이지 2 · 오프셋 8','Page 2 · offset 8'],['프레임 7로 매핑','Map to frame 7'],['물리 주소 28,680','Physical: 28,680']]),edges:[[0,1],[1,2],[2,3]]},
 'os-filesystems':{title:['파일 이름과 열린 파일 참조 구분하기','From a pathname to an open file reference'],caption:['Linux에서 파일을 여는 과정을 단순화했습니다. 경로로 파일을 찾은 뒤 열린 파일 상태를 만들고 프로세스의 디스크립터로 참조합니다.','Simplified Linux open: resolve the path, create open-file state, and refer to it through a process file descriptor.'],nodes:row([['경로','Pathname'],['VFS · 파일 찾기','VFS · resolve file'],['열린 파일 상태','Open-file state'],['파일 디스크립터','File descriptor']]),edges:[[0,1],[1,2],[2,3]]},
 'os-io-interrupts':{title:['장치 작업과 완료 처리','Device work and completion handling'],caption:['인터럽트를 사용하는 I/O 완료의 예시입니다. 캐시나 폴링을 쓰는 경로는 다를 수 있고, 준비 상태로 바뀐 스레드가 즉시 실행되지는 않습니다.','An interrupt-driven completion example. Cache and polling paths differ; a ready thread is not guaranteed to run immediately.'],nodes:row([['I/O 요청','Submit I/O'],['장치 작업','Device work'],['인터럽트 처리','Handle interrupt'],['대기 작업 깨우기','Wake waiting task']]),edges:[[0,1],[1,2],[2,3]]},
 'os-synchronization':{title:['같은 순서로 락을 획득하기','Acquire locks in a consistent order'],caption:['X와 Y를 쓰는 모든 관련 코드가 같은 획득 순서를 지키는 예시입니다. 다른 자원 대기나 예외 경로도 함께 검토해야 합니다.','All code using X and Y follows the same acquisition order in this example. Other resource waits and exception paths still need review.'],nodes:row([['X 획득','Acquire X'],['Y 획득','Acquire Y'],['공유 상태 갱신','Update shared state'],['Y · X 해제','Release Y and X']]),edges:[[0,1],[1,2],[2,3]]},
 'os-ipc':{title:['요청과 응답을 작업 ID로 연결','Match a request and response by ID'],caption:['두 프로세스가 합의한 메시지 형식으로 통신하는 예시입니다. 전달 실패·시간 제한·중복 요청 처리는 별도로 설계해야 합니다.','Two processes use an agreed message format. Delivery failures, timeouts and duplicate requests require separate handling.'],nodes:row([['A: 요청 #42','A: request #42'],['통신 채널','IPC channel'],['B: 작업 처리','B: process task'],['A: 결과 #42 수신','A: receive #42']]),edges:[[0,1],[1,2],[2,3]]}
});
function body(config,lang){
 if(config.kind==='hierarchy')return `<rect x="35" y="20" width="675" height="215" rx="16" fill="#eaf1ec" stroke="#b8ccbe"/><text x="60" y="55">AI · ${lang==='en'?'Artificial Intelligence':'인공지능'}</text><rect x="185" y="75" width="495" height="135" rx="13" fill="#dce9df" stroke="#aec4b4"/><text x="210" y="106">ML · ${lang==='en'?'Machine Learning':'머신러닝'}</text><rect x="360" y="128" width="290" height="58" rx="10" fill="#52745e"/><text x="505" y="162" text-anchor="middle" fill="white">${lang==='en'?'Deep Learning':'딥러닝'}</text>`;
 if(config.kind==='network'){
  const layers=[[65,[85,155]],[270,[50,120,190]],[480,[85,155]],[670,[120]]];let out='';
  for(let i=0;i<layers.length-1;i++)for(const y of layers[i][1])for(const yy of layers[i+1][1])out+=`<line x1="${layers[i][0]}" y1="${y}" x2="${layers[i+1][0]}" y2="${yy}" stroke="#c2d3c8"/>`;
  layers.forEach(([x,ys],i)=>{ys.forEach(y=>out+=`<circle cx="${x}" cy="${y}" r="17" fill="${i===3?'#587963':'#e3eee6'}" stroke="#91b29b"/>`);out+=`<text x="${x}" y="235" text-anchor="middle">${pick([['입력','Input'],['은닉층 1','Hidden 1'],['은닉층 2','Hidden 2'],['출력','Output']][i],lang)}</text>`;});return out;
 }
 if(config.kind==='matrix'){
  let out=`<text x="315" y="28" text-anchor="middle">${lang==='en'?'Predicted positive':'양성 예측'}</text><text x="560" y="28" text-anchor="middle">${lang==='en'?'Predicted negative':'음성 예측'}</text>`;
  [[65,'TP',['올바른 탐지','Correct detection'],'#e2eee5'],[155,'FP',['오탐','False alarm'],'#f5eee3']].forEach(([y,key,label,fill],i)=>{out+=`<text x="95" y="${y+40}" text-anchor="middle">${lang==='en'?(i?'Actual negative':'Actual positive'):(i?'실제 음성':'실제 양성')}</text>`;out+=`<rect x="195" y="${y}" width="230" height="75" rx="8" fill="${fill}"/><text x="310" y="${y+30}" text-anchor="middle">${key}</text><text class="diagram-sub" x="310" y="${y+55}" text-anchor="middle">${pick(label,lang)}</text>`;const label2=i?['올바른 제외','Correct rejection']:['미탐','Missed detection'];out+=`<rect x="440" y="${y}" width="230" height="75" rx="8" fill="${i?'#e2eee5':'#f5eee3'}"/><text x="555" y="${y+30}" text-anchor="middle">${i?'TN':'FN'}</text><text class="diagram-sub" x="555" y="${y+55}" text-anchor="middle">${pick(label2,lang)}</text>`;});return out;
 }
 let out='';
 for(const [from,to]of config.edges){const a=config.nodes[from],b=config.nodes[to];const dx=b.x+b.w/2-a.x-a.w/2,dy=b.y-a.y;const horizontal=Math.abs(dy)<80||Math.abs(dx)>250;const x1=horizontal?(dx>=0?a.x+a.w:a.x):a.x+a.w/2,y1=horizontal?a.y+30:(dy>=0?a.y+60:a.y),x2=horizontal?(dx>=0?b.x:b.x+b.w):b.x+b.w/2,y2=horizontal?b.y+30:(dy>=0?b.y:b.y+60);out+=`<path d="M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2} ${y2}" fill="none" stroke="#9bb5a3" stroke-width="1.6" marker-end="url(#arrow)"/>`;}
 if(config.loop)out+='<path d="M 630 143 V 195 H 94 V 146" fill="none" stroke="#9bb5a3" stroke-width="1.5" stroke-dasharray="5 4" marker-end="url(#arrow)"/>';
 for(const node of config.nodes){const label=pick(node.label,lang),sub=pick(node.sub,lang);out+=`<rect x="${node.x}" y="${node.y}" width="${node.w}" height="60" rx="10" fill="#edf4ef" stroke="#c5d7cb"/><text x="${node.x+node.w/2}" y="${node.y+(sub?26:35)}" text-anchor="middle">${esc(label)}</text>${sub?`<text class="diagram-sub" x="${node.x+node.w/2}" y="${node.y+46}" text-anchor="middle">${esc(sub)}</text>`:''}`;}
 return out;
}
export function diagram(slug,lang){const c=configs[slug];if(!c)return '';const title=pick(c.title,lang),caption=pick(c.caption,lang),height=c.height||260;
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 ${height}" role="img" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">${esc(title)}</title><desc id="diagram-desc">${esc(caption)}</desc><style>text{font:14px system-ui,sans-serif;fill:#496852}.diagram-sub{font-size:11px;fill:#71877a}text[fill="white"]{fill:white}</style><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#9bb5a3"/></marker></defs>${body(c,lang)}</svg>`;
 return `<figure class="concept-diagram"><div class="diagram-heading"><strong>${esc(title)}</strong><a download="${slug}-${lang}.svg" href="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}">SVG ↓</a></div><div class="diagram-scroll">${svg}</div><figcaption>${esc(caption)}<span>${lang==='en'?'Explanatory diagram created for whateveriwant · not a source figure':'whateveriwant 자체 제작 설명 도식 · 원문 이미지 아님'}</span></figcaption></figure>`;
}

Object.assign(configs,{
 'backpropagation':{title:['미분과 갱신의 역할 분리','Separate differentiation from updates'],caption:['역전파는 기울기를 구합니다. 파라미터 갱신은 옵티마이저의 별도 단계입니다.','Backpropagation computes gradients; an optimizer separately updates parameters.'],nodes:row([['예측 계산','Forward pass'],['손실 계산','Compute loss'],['기울기 계산','Backward pass'],['파라미터 갱신','Optimizer step']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'context-retrieval':{title:['검색에서 문맥 구성까지','From retrieval to context'],caption:['후보와 문맥에는 요청자의 접근 권한을 적용합니다. 검색 성공과 답변 정확성은 따로 평가합니다.','Apply access control to retrieval and context. Evaluate retrieval and answer accuracy separately.'],nodes:row([['권한 있는 후보','Authorized candidates'],['재순위화','Rerank'],['문맥 + 출처','Context + sources'],['답변 검증','Verify answer']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-graphs-search':{title:['의존성은 실행 순서를 제한한다','Dependencies constrain execution order'],caption:['정규화 이후의 두 작업은 서로 독립이라는 가정 아래 병렬 실행할 수 있습니다.','The last two tasks may run in parallel if they have no dependency on each other.'],nodes:[n(25,80,['원본 읽기','Read data']),n(255,80,['정규화','Normalize']),n(500,15,['특징 생성','Build features'],'',190),n(500,145,['품질 검사','Check quality'],'',190)],edges:[[0,1],[1,2],[1,3]],height:250}
});

Object.assign(configs,{
 'network-can-bus':{title:['CAN 노드에서 공유 버스까지','From a CAN node to the shared bus'],caption:['한 노드의 구성입니다. 다른 노드도 각자의 트랜시버로 같은 버스에 연결합니다. 배선과 종단은 생략했습니다.','One node and its connection. Other nodes attach through their own transceivers. Wiring and termination are omitted.'],nodes:row([['ECU 애플리케이션','ECU application'],['CAN 컨트롤러','CAN controller'],['트랜시버','Transceiver'],['공유 CAN 버스','Shared CAN bus']]),edges:[[0,1],[1,2],[2,3]]},
 'network-lin':{title:['LIN의 헤더와 응답 순서','LIN header and response order'],caption:['스케줄의 두 슬롯을 단순화했습니다. commander가 헤더를 보내고 해당 프레임의 publisher가 응답합니다. 같은 노드가 두 역할을 맡을 수도 있습니다.','Two simplified schedule slots. The commander sends headers; each designated publisher responds. One node may perform both roles.'],nodes:row([['헤더 A','Header A'],['응답 A','Response A'],['다음 슬롯: 헤더 B','Next slot: header B'],['응답 B','Response B']]),edges:[[0,1],[1,2],[2,3]]},
 'network-layers-packets':{title:['보내는 데이터의 캡슐화','Encapsulation on the sending side'],caption:['각 층은 전달에 필요한 정보를 더합니다. 받는 쪽은 이를 해석하며, 실제 헤더 구조와 중간 장비는 생략했습니다.','Each layer adds delivery information. The receiver interprets it; headers and intermediate devices are simplified.'],nodes:row([['애플리케이션','Application'],['전송 계층','Transport'],['IP 패킷','IP packet'],['링크 프레임','Link frame']]),edges:[[0,1],[1,2],[2,3]]},
 'network-routing-nat':{title:['다음 홉을 따라가는 전달','Forwarding through next hops'],caption:['원격 서버로 갈 때 첫 링크의 목적지는 게이트웨이입니다. 링크 프레임은 홉마다 다시 구성됩니다. NAT 적용 여부는 경로에 따라 다릅니다.','The first link targets the gateway. Link frames are rebuilt at each hop. NAT depends on the path.'],nodes:row([['클라이언트','Client'],['게이트웨이','Gateway'],['중간 라우터','Transit router'],['서버 네트워크','Server network']]),edges:[[0,1],[1,2],[2,3]]},
 'network-dns-dhcp':{title:['리졸버가 필요한 정보를 조회한다','The resolver obtains the needed information'],caption:['캐시에 없을 때의 단순화된 조회 관계입니다. 각 서버는 다음 단계나 최종 정보를 응답하며, 리졸버가 후속 조회를 수행합니다.','Simplified uncached lookup. Servers provide referrals or answers; the resolver makes subsequent queries.'],nodes:[n(15,120,['클라이언트','Client']),n(215,120,['재귀 리졸버','Recursive resolver'],'',175),n(495,15,['루트','Root'],'',200),n(495,125,['상위 도메인','Top-level domain'],'',200),n(495,235,['권한 서버','Authoritative server'],'',200)],edges:[[0,1],[1,2],[1,3],[1,4]],height:330}
});

Object.assign(configs,{
 'vulnerabilities-sql-injection':{title:['쿼리 구조와 값 분리하기','Keep query structure and values separate'],caption:['애플리케이션이 쿼리 구조를 정하고 입력은 값으로 바인딩합니다. 동적 식별자 선택은 별도 허용 목록으로 관리합니다.','The application defines the query; input is bound as a value. Dynamic identifiers need a separate allowlist.'],nodes:[n(25,30,['쿼리 구조','Query structure'],'',180),n(25,155,['입력 값','Input value'],'',180),n(300,95,['매개변수 바인딩','Parameter binding'],'',190),n(560,95,['DB 실행','DB execution'],'',160)],edges:[[0,2],[1,2],[2,3]]},
 'vulnerabilities-access-control':{title:['요청마다 인가 정책 확인','Check authorization for each request'],caption:['주체·대상·행동·조직 경계를 정책으로 판단합니다. 확인되지 않은 요청은 기본 거절하고, 허용된 요청만 처리합니다.','Evaluate subject, object, action and tenant boundaries. Deny by default; process authorized requests only.'],nodes:[n(20,95,['요청','Request'],'',150),n(260,95,['정책 검사','Policy check'],'',190),n(540,30,['허용: 처리','Allow: process'],'',180),n(540,170,['거절','Deny'],'',180)],edges:[[0,1],[1,2],[1,3]]}
});

Object.assign(configs,{
 'crypto-symmetric-encryption':{title:['인증 암호화(AEAD)의 흐름','Authenticated encryption (AEAD) flow'],caption:['하나의 비밀키와 유일한 nonce로 암호화하면 암호문과 인증 태그가 함께 나옵니다. 같은 키로 nonce를 재사용하면 안 됩니다.','One secret key and a unique nonce produce ciphertext plus an authentication tag. Never reuse a nonce with the same key.'],nodes:row([['평문 · 키 · nonce','Plaintext · key · nonce'],['AES-GCM','AES-GCM'],['암호문','Ciphertext'],['+ 인증 태그','+ auth tag']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-asymmetric-encryption':{title:['하이브리드 암호화','Hybrid encryption'],caption:['데이터는 빠른 대칭키로 암호화하고, 그 대칭키만 수신자의 공개키로 감쌉니다. 수신자는 개인키로 대칭키를 풀어 복호화합니다.','Encrypt data with a fast symmetric key; wrap only that key with the recipient public key. The recipient unwraps it with the private key.'],nodes:row([['평문','Plaintext'],['대칭키로 암호화','Encrypt with data key'],['대칭키를 공개키로 감쌈','Wrap key with public key'],['개인키로 복원 → 복호화','Unwrap with private key']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-hashing':{title:['해시: 고정 길이 요약','Hashing: a fixed-length digest'],caption:['임의 길이 입력을 고정 길이 요약으로 바꿉니다. 되돌릴 수 없고, 입력이 조금만 바뀌어도 요약이 크게 달라집니다.','Maps any input to a fixed-length digest. It is one-way, and a tiny input change alters the digest completely.'],nodes:row([['임의 길이 입력','Any-length input'],['해시 함수 · SHA-256','Hash · SHA-256'],['고정 길이 요약','Fixed digest'],['변경 시 요약도 바뀜','Changes if input changes']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-mac-and-signatures':{title:['서명: 개인키로 만들고 공개키로 검증','Sign with private, verify with public'],caption:['서명자는 개인키로 서명하고, 누구나 공개키로 검증합니다. 개인키 보유자만 만들 수 있어 무결성과 출처를 함께 보장합니다.','The signer uses a private key; anyone verifies with the public key. Only the key holder can sign, giving integrity and origin.'],nodes:[n(25,90,['메시지','Message']),n(230,25,['개인키로 서명','Sign · private key'],'',185),n(230,155,['공개키로 검증','Verify · public key'],'',185),n(555,90,['무결성 + 출처','Integrity + origin'],'',165)],edges:[[0,1],[1,2],[2,3]],height:250},
 'crypto-key-exchange':{title:['Diffie-Hellman 키 교환','Diffie-Hellman key exchange'],caption:['각자 개인 비밀을 감춘 공개값만 교환해 같은 공유 비밀을 유도합니다. 도청자는 공개값만 보므로 공유 비밀을 계산할 수 없습니다.','Each party exchanges only a public value derived from a private secret, yet both derive the same shared secret. An eavesdropper cannot.'],nodes:[n(25,30,['A 비밀 a','A secret a']),n(25,155,['B 비밀 b','B secret b']),n(300,30,['A 공개 g^a','A public g^a']),n(300,155,['B 공개 g^b','B public g^b']),n(555,90,['공유 비밀','Shared secret'],'g^ab',165)],edges:[[0,2],[1,3],[2,4],[3,4]],height:250},
 'crypto-pki-and-certificates':{title:['인증서 신뢰 사슬','Certificate chain of trust'],caption:['루트 CA가 중간 CA를, 중간 CA가 서버 인증서를 서명합니다. 검증자는 서버부터 신뢰하는 루트까지 서명을 거슬러 확인합니다.','A root CA signs an intermediate, which signs the server certificate. The verifier follows signatures back to a trusted root.'],nodes:row([['루트 CA','Root CA'],['중간 CA','Intermediate CA'],['서버 인증서','Server certificate'],['브라우저 검증','Browser verifies']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-rsa':{title:['RSA 키 생성','RSA key generation'],caption:['두 소수 p, q로 n을 만들고 공개 지수 e와 개인 지수 d를 구합니다. n을 인수분해하기 어려워 개인키를 역산할 수 없습니다.','Form n from primes p, q and derive public e and private d. Factoring n is hard, so the private key cannot be recovered.'],nodes:row([['소수 p · q','Primes p · q'],['n = p · q','n = p · q'],['e · d 계산','Compute e · d'],['공개(n,e) · 개인(d)','Public (n,e) · private (d)']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-elliptic-curve':{title:['ECC: 스칼라 곱 한 방향','ECC: one-way scalar multiplication'],caption:['개인키 스칼라 k로 공개키 점 k·G를 쉽게 계산하지만, 점만 보고 k를 역산하는 것(ECDLP)은 매우 어렵습니다.','Computing the public point k·G from scalar k is easy; recovering k from the point (ECDLP) is very hard.'],nodes:row([['개인키 k','Private scalar k'],['k · G 계산','Compute k · G'],['공개키(점)','Public key (point)'],['역산은 어려움','Reversal is hard']]),edges:[[0,1],[1,2],[2,3]]},
 'crypto-password-storage':{title:['비밀번호 저장과 검증','Storing and checking a password'],caption:['비밀번호에 사용자별 salt를 붙여 느린 해시로 저장합니다. 로그인 시 같은 방식으로 다시 계산해 비교하며, 원문은 복원하지 않습니다.','Add a per-user salt and store a slow hash. On login, recompute the same way and compare; the original is never recovered.'],nodes:row([['비밀번호 + salt','Password + salt'],['Argon2id · 느린 해시','Argon2id · slow hash'],['저장값','Stored hash'],['로그인 시 재계산·비교','Recompute & compare']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-sorting':{title:['병합 정렬: 분할과 병합','Merge sort: divide and merge'],caption:['배열을 반씩 나눠 각각 정렬한 뒤 병합합니다. 분할 정복으로 항상 O(n log n)이며 안정 정렬입니다.','Split in half, sort each part, then merge. This divide-and-conquer approach is always O(n log n) and stable.'],nodes:row([['[8, 3, 5, 1]','[8, 3, 5, 1]'],['반으로 분할','Split in half'],['각각 정렬','Sort each half'],['병합 → [1,3,5,8]','Merge → [1,3,5,8]']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-searching':{title:['이진 탐색: 절반씩 좁히기','Binary search: halving the range'],caption:['정렬된 데이터에서 중간값과 비교해 후보의 절반을 버립니다. 이를 반복해 O(log n)에 찾습니다.','In sorted data, compare with the middle and discard half the candidates. Repeat to find in O(log n).'],nodes:row([['정렬 배열','Sorted array'],['중간값과 비교','Compare middle'],['절반 버림','Discard half'],['반복 → 발견','Repeat → found']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'algorithms-hash-tables':{title:['해시 테이블: 키에서 버킷으로','Hash table: key to bucket'],caption:['해시 함수가 키를 버킷 인덱스로 바꿔 평균 O(1)에 접근합니다. 다른 키가 같은 버킷으로 가면(충돌) 체이닝 등으로 처리합니다.','A hash function maps a key to a bucket index for average O(1) access. Collisions are handled by chaining or probing.'],nodes:row([['키','Key'],['해시 함수','Hash function'],['버킷 인덱스','Bucket index'],['값 저장 · 조회','Store · look up']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-trees-and-bst':{title:['이진 탐색 트리의 탐색 경로','Search path in a BST'],caption:['왼쪽<노드<오른쪽 불변식을 따라 값을 비교하며 한쪽으로 내려갑니다. 균형이 유지되면 O(log n)입니다.','Follow the left<node<right invariant, comparing and descending one side. Balanced trees give O(log n).'],nodes:[n(288,10,'50',['루트','Root'],150),n(95,115,'30',['작으면 왼쪽','Smaller → left'],170),n(510,115,'70',['크면 오른쪽','Larger → right'],170),n(25,215,'20','',140),n(245,215,'40','',140)],edges:[[0,1],[0,2],[1,3],[1,4]],height:295},
 'algorithms-heaps-priority-queues':{title:['힙: 최우선 원소 꺼내기','Heap: removing the top'],caption:['힙 성질을 유지하며 삽입·삭제는 O(log n), 최상단(최우선) 조회는 O(1)입니다. 전체 정렬 없이 최우선만 반복해 꺼낼 때 유리합니다.','Insertions and removals are O(log n); reading the top is O(1). Ideal when you repeatedly need the highest-priority item.'],nodes:row([['삽입','Insert'],['힙 성질 유지 · sift','Restore heap · sift'],['최상단 = 최우선','Top = highest priority'],['pop 후 재정렬','Pop, then re-heapify']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'algorithms-dynamic-programming':{title:['겹치는 부분 문제를 재사용','Reuse overlapping subproblems'],caption:['문제를 부분 문제로 나누되, 같은 부분 문제를 한 번만 계산해 저장하고 재사용합니다. 지수 시간이 선형·다항 시간으로 줄어듭니다.','Break into subproblems, but compute each overlapping one once and reuse it. Exponential work drops to linear or polynomial.'],nodes:row([['부분 문제로 분해','Split into subproblems'],['겹치는 부분 문제','Overlapping subproblems'],['한 번만 계산·저장','Compute once · store'],['재사용 → 빠름','Reuse → fast']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-backtracking':{title:['백트래킹: 확장하고 되돌리기','Backtracking: extend and undo'],caption:['부분 해를 확장하다 제약을 어기면 되돌아가 다른 선택을 시도합니다. 불가능한 경로를 일찍 잘라(가지치기) 탐색량을 줄입니다.','Extend a partial solution; on a constraint violation, back up and try another choice. Pruning cuts impossible paths early.'],nodes:row([['부분 해 확장','Extend partial solution'],['제약 검사','Check constraints'],['위반 시 되돌림','Undo on violation'],['완성 시 해 기록','Record complete solution']]),edges:[[0,1],[1,2],[2,3]],loop:true}
});

Object.assign(configs,{
 'vulnerabilities-xss':{title:['출력 문맥에 맞는 인코딩','Encode for the output context'],caption:['신뢰할 수 없는 입력을 HTML·속성·JS 등 출력 문맥에 맞게 인코딩하면 데이터로만 표시되고 코드로 실행되지 않습니다.','Encoding untrusted input for its output context (HTML, attribute, JS) makes it render as data, not execute as code.'],nodes:row([['신뢰할 수 없는 입력','Untrusted input'],['출력 문맥 판별','Identify context'],['문맥별 인코딩','Context-aware encoding'],['데이터로만 표시','Rendered as data']]),edges:[[0,1],[1,2],[2,3]]},
 'vulnerabilities-csrf':{title:['요청 의도와 출처 확인','Verify request intent and origin'],caption:['브라우저는 쿠키를 자동 첨부하므로, 상태 변경 요청은 CSRF 토큰과 Origin·SameSite로 사용자의 의도를 확인해야 합니다.','Browsers attach cookies automatically, so state-changing requests must confirm intent via a CSRF token and Origin/SameSite.'],nodes:row([['쿠키 자동 첨부','Cookie auto-attached'],['상태 변경 요청','State-changing request'],['토큰·Origin 확인','Check token · Origin'],['의도된 요청만 처리','Only intended requests']]),edges:[[0,1],[1,2],[2,3]]},
 'vulnerabilities-ssrf':{title:['서버 요청 대상 제한','Constrain server-side request targets'],caption:['사용자가 준 URL을 그대로 요청하지 않고, 허용 목록과 DNS 해석 후의 실제 IP까지 검증해 내부·메타데이터 접근을 막습니다.','Do not fetch a user URL directly. Validate against an allowlist and the resolved IP to block internal and metadata access.'],nodes:row([['사용자 지정 URL','User-supplied URL'],['목적지 허용 목록','Destination allowlist'],['해석된 IP 검증','Validate resolved IP'],['허용 대상만 요청','Fetch allowed only']]),edges:[[0,1],[1,2],[2,3]]},
 'vulnerabilities-command-injection':{title:['셸을 거치지 않고 인자로 실행','Run with an argument array, no shell'],caption:['입력을 문자열 명령으로 합치지 않고 실행 파일과 인자 배열을 분리해 전달하면, 입력이 명령 구문으로 해석되지 않습니다.','Pass the executable and an argument array separately instead of building a shell string, so input is not parsed as command syntax.'],nodes:row([['사용자 입력','User input'],['인자 배열로 분리','Argument array'],['실행 파일 + 인자','Executable + args'],['명령 해석 안 됨','Not parsed as command']]),edges:[[0,1],[1,2],[2,3]]},
 'network-tcp-udp':{title:['TCP 3-way 핸드셰이크','TCP three-way handshake'],caption:['연결을 세우는 SYN → SYN-ACK → ACK 교환입니다. 이후 순서·재전송이 보장되는 스트림이 열립니다. UDP는 이 과정 없이 데이터그램을 보냅니다.','SYN → SYN-ACK → ACK establishes a connection, then an ordered, reliable stream. UDP sends datagrams with no handshake.'],nodes:row([['클라이언트 SYN','Client SYN'],['서버 SYN-ACK','Server SYN-ACK'],['클라이언트 ACK','Client ACK'],['연결 수립','Connection established']]),edges:[[0,1],[1,2],[2,3]]},
 'network-load-balancing':{title:['요청을 여러 서버로 분산','Distribute requests across servers'],caption:['로드 밸런서가 하나의 진입점에서 요청을 백엔드 풀로 나눕니다. 헬스체크로 죽은 서버를 빼고 복구되면 되돌립니다.','A load balancer spreads requests from one entry point to a backend pool, removing unhealthy servers via health checks.'],nodes:[n(25,90,['클라이언트','Client']),n(230,90,['로드 밸런서','Load balancer'],'',175),n(500,20,['백엔드 A','Backend A'],'',180),n(500,150,['백엔드 B','Backend B'],'',180)],edges:[[0,1],[1,2],[1,3]],height:245},
 'network-websockets':{title:['HTTP에서 양방향 채널로','From HTTP to a bidirectional channel'],caption:['HTTP 업그레이드 요청에 서버가 101로 응답하면 같은 연결이 양방향 채널로 전환되어, 서버도 먼저 메시지를 보낼 수 있습니다.','After an HTTP upgrade and a 101 response, the same connection becomes bidirectional and the server can push first.'],nodes:row([['HTTP GET + Upgrade','HTTP GET + Upgrade'],['101 Switching','101 Switching'],['양방향 채널','Bidirectional channel'],['서버도 먼저 전송','Server can push']]),edges:[[0,1],[1,2],[2,3]]},
 'os-signals':{title:['시그널을 안전하게 처리하기','Handling a signal safely'],caption:['핸들러는 플래그만 설정하고, 실제 정리는 메인 루프에서 수행합니다. 핸들러 안에서는 async-signal-safe 함수만 써야 합니다.','The handler only sets a flag; cleanup happens in the main loop. Only async-signal-safe functions are allowed in a handler.'],nodes:row([['SIGTERM 전달','SIGTERM delivered'],['핸들러: 플래그 설정','Handler: set flag'],['메인 루프서 감지','Main loop checks flag'],['정리 후 종료','Clean up and exit']]),edges:[[0,1],[1,2],[2,3]]},
 'os-containers-namespaces':{title:['컨테이너를 이루는 커널 기능','Kernel features behind a container'],caption:['컨테이너는 별도 커널이 아니라, 네임스페이스(무엇을 보는가)와 cgroups(얼마나 쓰는가)로 격리된 프로세스입니다.','A container is not a separate kernel but a process isolated by namespaces (what it sees) and cgroups (how much it uses).'],nodes:row([['프로세스','Process'],['네임스페이스 · 격리된 뷰','Namespaces · isolated view'],['cgroups · 자원 제한','cgroups · resource limits'],['격리된 컨테이너','Isolated container']]),edges:[[0,1],[1,2],[2,3]]},
 'os-memory-allocation':{title:['힙 할당과 반환','Heap allocation and release'],caption:['malloc은 힙에서 요청 크기만큼 블록을 잘라 포인터를 돌려주고, free로 반환합니다. 반환 뒤 그 포인터를 쓰면 use-after-free입니다.','malloc carves a block from the heap and returns a pointer; free releases it. Using a pointer after free is use-after-free.'],nodes:row([['malloc 요청','malloc request'],['힙에서 블록 분할','Carve heap block'],['포인터 반환','Return pointer'],['free로 반환','Release with free']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'cs-cache-memory-hierarchy':{title:['메모리 계층: 빠르고 작음 ↔ 느리고 큼','Memory hierarchy: fast-small ↔ slow-large'],caption:['레지스터에서 저장장치로 갈수록 느리지만 커집니다. 자주 쓰는 데이터를 위 계층에 두는 지역성이 성능을 좌우합니다.','From registers to storage, each level is slower but larger. Locality — keeping hot data high — drives performance.'],nodes:row([['레지스터 · <1ns','Registers · <1ns'],['L1–L3 캐시 · ns','L1–L3 cache · ns'],['RAM · ~100ns','RAM · ~100ns'],['저장장치 · µs–ms','Storage · µs–ms']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-type-systems':{title:['정적 타입 검사가 잡는 오류','What static type checking catches'],caption:['정적 타입은 실행 전 컴파일 단계에서 타입 불일치를 걸러 냅니다. 그 부류의 오류는 배포된 코드에서 나타나지 않습니다.','Static typing catches type mismatches at compile time, before execution, so that class of error never reaches production.'],nodes:row([['소스 코드','Source code'],['타입 검사','Type check'],['불일치 = 오류','Mismatch = error'],['실행 전 차단','Blocked before run']]),edges:[[0,1],[1,2],[2,3]]}
});

Object.assign(configs,{
 'algorithms-shortest-paths':{title:['다익스트라: 가까운 것부터 확정','Dijkstra: settle the nearest first'],caption:['미확정 정점 중 가장 가까운 것을 확정하고 그 이웃 거리를 완화합니다. 우선순위 큐로 반복하며 음이 아닌 가중치에서만 옳습니다.','Settle the nearest unsettled vertex and relax its neighbours, repeating via a priority queue. Correct only for non-negative weights.'],nodes:row([['출발점 거리 0','Source distance 0'],['가장 가까운 미확정 확정','Settle nearest'],['이웃 거리 완화','Relax neighbours'],['반복 → 최단 거리','Repeat → shortest'],]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'algorithms-string-matching':{title:['KMP: 실패 정보로 건너뛰기','KMP: skip using failure info'],caption:['불일치가 나면 패턴을 1칸씩 밀지 않고 실패 함수로 건너뜁니다. 텍스트 포인터는 되돌아가지 않아 O(n+m)입니다.','On a mismatch, skip via the failure function instead of shifting by one. The text pointer never backtracks, giving O(n+m).'],nodes:row([['텍스트 · 패턴','Text · pattern'],['불일치 발생','Mismatch'],['실패 함수로 건너뜀','Skip via failure fn'],['포인터 안 되돌림','No backtracking']]),edges:[[0,1],[1,2],[2,3]]}
});

Object.assign(configs,{
 'security-principles':{title:['심층 방어: 겹겹의 통제','Defense in depth: layered controls'],caption:['자산과 신뢰 경계를 식별하고 최소 권한과 여러 통제를 겹칩니다. 한 통제가 실패해도 남은 계층이 피해를 제한합니다.','Identify assets and trust boundaries, then layer least privilege and multiple controls so one failure does not end containment.'],nodes:row([['자산·위협 식별','Identify assets · threats'],['신뢰 경계','Trust boundaries'],['계층별 통제','Layered controls'],['실패해도 잔여 보호','Residual protection']]),edges:[[0,1],[1,2],[2,3]]},
 'security-authentication-authorization':{title:['인증과 인가는 다른 질문','Authentication vs authorization'],caption:['인증은 "누구인가", 인가는 "무엇을 해도 되는가"입니다. 신원을 확인한 뒤, 요청마다 자원·행동 권한을 별도로 검사합니다.','Authentication asks who; authorization asks what is allowed. Verify identity, then check resource/action permission per request.'],nodes:row([['신원 주장','Claimed identity'],['인증: 누구인가','Authenticate: who'],['인가: 무엇을 허용','Authorize: what'],['자원 접근','Access resource']]),edges:[[0,1],[1,2],[2,3]]},
 'security-web-security':{title:['요청이 지나는 신뢰 경계','Trust boundaries a request crosses'],caption:['브라우저 → 서버 → 앱 → DB의 각 경계에서 검증이 필요합니다. 폼 제한을 믿지 말고 서버가 입력·인가·값 바인딩을 확인합니다.','Each boundary needs its own checks. Do not trust the form; the server validates input, authorization and value binding.'],nodes:row([['브라우저','Browser'],['서버: 입력 검증','Server: validate input'],['앱: 인가 확인','App: authorize'],['DB: 값 바인딩','DB: bind values']]),edges:[[0,1],[1,2],[2,3]]},
 'security-api-security':{title:['OAuth 2.0 + PKCE 흐름','OAuth 2.0 with PKCE'],caption:['앱이 code_challenge와 함께 인가를 요청하고, 받은 코드를 code_verifier로 교환해 토큰을 얻습니다. 토큰은 발급자·수신자·수명을 검증합니다.','The app requests authorization with a code_challenge, then exchanges the code with its code_verifier for tokens, which are validated (iss/aud/exp).'],nodes:row([['/authorize + PKCE','/authorize + PKCE'],['인가 코드','Authorization code'],['/token 교환','/token exchange'],['access token 검증','Validate access token']]),edges:[[0,1],[1,2],[2,3]]},
 'security-zero-trust':{title:['제로 트러스트: 매 요청 검증','Zero trust: verify every request'],caption:['위치가 아니라 정책 결정 지점(PDP)이 신원·기기·맥락으로 판단하고, 집행 지점(PEP)이 강제합니다. 세션은 지속적으로 재평가됩니다.','Not location but a policy decision point (PDP) decides on identity, device and context; a policy enforcement point (PEP) enforces it, continuously re-evaluated.'],nodes:row([['요청(위치 무관)','Request (any location)'],['정책 결정 PDP','Decision · PDP'],['집행 PEP','Enforce · PEP'],['세션마다 재평가','Re-evaluate session']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'security-email-authentication':{title:['SPF·DKIM·DMARC 정렬','SPF, DKIM and DMARC alignment'],caption:['SPF는 발신 IP, DKIM은 메시지 서명을 검증하고, DMARC는 이 결과가 From 도메인과 정렬되는지와 실패 정책을 정합니다.','SPF checks sending IP, DKIM checks the message signature, and DMARC requires these to align with the From domain plus a failure policy.'],nodes:row([['발신 메일','Outgoing mail'],['SPF: 발신 IP','SPF: sender IP'],['DKIM: 서명','DKIM: signature'],['DMARC: 정렬·정책','DMARC: align · policy']]),edges:[[0,1],[1,2],[2,3]]},
 'security-availability-dos':{title:['토큰 버킷 레이트 리밋','Token-bucket rate limiting'],caption:['일정 속도로 토큰을 채우고 요청마다 하나씩 소비합니다. 토큰이 있으면 허용해 버스트를 흡수하고, 없으면 거절(429)합니다.','Refill tokens at a steady rate and spend one per request. Allow while tokens remain (absorbing bursts); otherwise reject (429).'],nodes:row([['요청 도착','Request arrives'],['토큰 소비 시도','Try to spend token'],['있으면 허용','Allow if available'],['없으면 429 거절','Else reject (429)']]),edges:[[0,1],[1,2],[2,3]]},
 'security-software-supply-chain':{title:['빌드 출처를 검증하는 사슬','Verifying build provenance'],caption:['소스에서 빌드까지의 각 단계를 서명·SBOM으로 기록하고, 배포 전 그 출처와 무결성을 검증합니다.','Record each step from source to build with signatures and an SBOM, then verify provenance and integrity before deployment.'],nodes:row([['소스','Source'],['빌드','Build'],['서명 · SBOM','Sign · SBOM'],['배포 전 검증','Verify before deploy']]),edges:[[0,1],[1,2],[2,3]]},
 'security-logging-incident-response':{title:['사고 대응의 순환','The incident-response loop'],caption:['로그를 모아 탐지하고, 조사·억제 후 복구하며, 배운 것을 통제 개선으로 되돌립니다.','Collect logs to detect, then investigate and contain, recover, and feed lessons back into improved controls.'],nodes:row([['로그 수집','Collect logs'],['탐지·경보','Detect · alert'],['조사·억제','Investigate · contain'],['복구·개선','Recover · improve']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'security-cloud-identity-secrets':{title:['워크로드 신원과 시크릿','Workload identity and secrets'],caption:['장기 키를 코드에 두지 않고, 워크로드 신원으로 단기 자격 증명을 시크릿 저장소에서 받아 최소 권한으로 접근합니다.','Instead of long-lived keys in code, a workload identity fetches short-lived credentials from a secrets store for least-privilege access.'],nodes:row([['워크로드 신원','Workload identity'],['단기 자격 증명','Short-lived credential'],['시크릿 저장소','Secrets store'],['최소 권한 접근','Least-privilege access']]),edges:[[0,1],[1,2],[2,3]]},
 'security-hardware-security':{title:['하드웨어 신뢰 사슬','Hardware chain of trust'],caption:['하드웨어 신뢰 뿌리가 부팅 각 단계를 측정(PCR)하고 서명을 검증합니다. 원격 증명으로 알려진 상태로 부팅했는지 확인합니다.','A hardware root of trust measures each boot stage (PCR) and verifies signatures; remote attestation confirms a known-good boot.'],nodes:row([['신뢰 뿌리(TPM)','Root of trust (TPM)'],['부팅 단계 측정','Measure boot (PCR)'],['서명 검증','Verify signatures'],['원격 증명','Remote attestation']]),edges:[[0,1],[1,2],[2,3]]}
});

Object.assign(configs,{
 'ai-for-security-fundamentals':{title:['보안 데이터에서 분석가 판단까지','From security data to analyst decisions'],caption:['로그를 특징·라벨로 만들고 모델이 점수를 내지만, 최종 판단과 권한 있는 대응은 분석가가 맡습니다.','Turn logs into features and labels; the model scores, but the analyst makes the final, privileged decision.'],nodes:row([['보안 로그','Security logs'],['특징 · 라벨','Features · labels'],['모델 점수','Model score'],['분석가 검토','Analyst review']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-for-security-detection-evaluation':{title:['정확도가 높아도 경보는 오탐투성이','High accuracy, mostly false alarms'],caption:['악성이 드문(낮은 기저율) 상황에서는 정확도 99%여도 경보 대부분이 오탐일 수 있습니다. 정밀도·재현율로 판단합니다.','When malicious events are rare (low base rate), even 99% accuracy can make most alerts false. Judge with precision and recall.'],nodes:row([['정확도 99%','99% accuracy'],['드문 양성(기저율)','Rare positives'],['경보 대부분 오탐','Alerts mostly false'],['정밀도·재현율로 판단','Judge by precision/recall']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-for-security-log-anomaly-detection':{title:['기준선에서 벗어남을 점수화','Score deviation from a baseline'],caption:['평소 패턴을 학습해 기준선을 세우고, 현재 활동의 이탈을 점수로 냅니다. 이상은 곧 악성이 아니므로 맥락을 붙여 검토합니다.','Learn a baseline of normal behaviour and score how far current activity deviates. Anomalous is not malicious — add context before acting.'],nodes:row([['평소 기준선 학습','Learn baseline'],['현재 활동','Current activity'],['이탈 점수','Deviation score'],['맥락 검토','Review with context']]),edges:[[0,1],[1,2],[2,3]]},
 'security-for-ai-adversarial-ml':{title:['회피: 미세 변형으로 오분류 유도','Evasion: perturb to force misclassification'],caption:['공격자가 사람은 못 느낄 작은 변형을 입력에 더해 모델의 예측을 뒤집습니다. 방어는 견고성 평가와 심층 방어로 이뤄집니다.','An attacker adds a small, imperceptible perturbation to flip the model prediction. Defense relies on robustness evaluation and depth.'],nodes:[n(25,90,['정상 입력','Clean input']),n(240,90,['미세 변형 +ε','Perturb +ε'],'',175),n(500,25,['모델','Model'],'',150),n(500,155,['오분류','Misclassified'],'',150)],edges:[[0,1],[1,2],[2,3]],height:245},
 'security-for-ai-llm-prompt-injection':{title:['모델 밖에서 피해 제한','Contain impact outside the model'],caption:['신뢰할 수 없는 콘텐츠를 데이터로만 표시하고, 모델 출력은 제안으로만 받으며, 실제 실행 여부는 정책 코드가 결정합니다.','Mark untrusted content as data, take model output only as a proposal, and let policy code decide what actually executes.'],nodes:row([['신뢰 못할 콘텐츠','Untrusted content'],['모델: 데이터로 표시','Model: as data'],['출력 = 제안만','Output = proposal'],['정책이 실행 결정','Policy decides run']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-for-security-soar-automation':{title:['위험도에 따른 자동/수동 분기','Auto vs human by risk'],caption:['부작용 없는 보강은 자동으로 하고, 위험도가 낮으면 자동 종료, 파괴적 조치는 사람 승인을 거칩니다. 모든 결정은 근거를 남깁니다.','Enrichment runs automatically; low risk auto-closes, but destructive actions need human approval — every decision records its rationale.'],nodes:[n(25,90,['경보','Alert']),n(230,90,['자동 보강','Auto-enrich'],'',170),n(455,25,['저위험: 자동 종료','Low: auto-close'],'',195),n(455,155,['고위험: 사람 승인','High: human approval'],'',195)],edges:[[0,1],[1,2],[1,3]],height:245},
 'ai-for-security-ueba-graph-detection':{title:['기준선과 관계 그래프로 탐지','Detect via baselines and graphs'],caption:['주체 자신·피어 그룹 기준으로 이탈을 보고, 계정·호스트를 노드로 이어 개별로는 안 보이는 경로(횡적 이동)를 드러냅니다.','Compare against the entity itself and its peers, and connect accounts/hosts as a graph to reveal paths (lateral movement) invisible per event.'],nodes:row([['주체별 기준선','Per-entity baseline'],['피어 그룹 비교','Peer-group compare'],['이탈 · 그래프 경로','Deviation · graph path'],['맥락으로 우선순위','Prioritize with context']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-for-security-malware-classification':{title:['정적·동적 특징으로 분류','Classify from static and dynamic features'],caption:['실행 없이 뽑는 정적 특징과 샌드박스 실행에서 얻는 동적 특징을 분류기에 넣습니다. 정적으로 걸러 의심스러운 것만 동적 분석에 보냅니다.','Feed static features (no execution) and dynamic features (sandbox) to a classifier; screen statically and send only suspicious files to dynamic analysis.'],nodes:[n(25,90,['파일','File']),n(240,25,['정적 특징','Static features'],'',180),n(240,155,['동적 특징(샌드박스)','Dynamic (sandbox)'],'',195),n(545,90,['분류기','Classifier'],'',160)],edges:[[0,1],[0,2],[1,3],[2,3]],height:245},
 'ai-for-security-threat-intel-enrichment':{title:['지표에 맥락을 붙여 우선순위화','Enrich indicators to prioritize'],caption:['관측 지표에 평판·신뢰도를 붙여 판단 가능하게 만듭니다. IP·해시는 바꾸기 쉬우므로 오래가는 공격자 행위(TTP)에 무게를 둡니다.','Add reputation and confidence so indicators become actionable. IPs and hashes change easily, so weight durable attacker behaviour (TTPs).'],nodes:row([['관측 지표(IP·해시)','Observed IOC'],['평판·신뢰도 보강','Enrich reputation'],['TTP에 무게','Weight TTPs'],['경보 우선순위','Alert priority']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-for-security-model-operations':{title:['배포 후 관측·재학습·롤백','Monitor, retrain, roll back'],caption:['배포한 모델의 성능과 분포 변화(드리프트)를 관측하고, 임계를 넘으면 재학습하거나 검증된 이전 버전으로 롤백합니다.','Monitor a deployed model for performance and drift; when thresholds break, retrain or roll back to a verified previous version.'],nodes:row([['배포 모델','Deployed model'],['성능·드리프트 관측','Monitor drift'],['임계 초과','Threshold breached'],['재학습·롤백','Retrain · roll back']]),edges:[[0,1],[1,2],[2,3]],loop:true}
});

Object.assign(configs,{
 'probability-statistics':{title:['표본에서 불확실성 있는 추정으로','From a sample to an uncertain estimate'],caption:['전체를 다 볼 수 없어 표본으로 모집단을 추정합니다. 추정에는 불확실성이 따르므로 신뢰구간처럼 범위로 표현합니다.','We estimate a population from a sample. Estimates carry uncertainty, expressed as a range such as a confidence interval.'],nodes:row([['모집단','Population'],['표본 추출','Sample'],['추정치','Estimate'],['불확실성 · 구간','Uncertainty · interval']]),edges:[[0,1],[1,2],[2,3]]},
 'model-selection-features':{title:['교차 검증으로 공정하게 비교','Compare fairly with cross-validation'],caption:['특징 파이프라인을 고정하고 교차 검증으로 설정을 비교한 뒤, 마지막에 테스트로 한 번만 평가합니다. 누수를 막는 것이 핵심입니다.','Fix the feature pipeline, compare settings via cross-validation, then evaluate once on test — preventing leakage is key.'],nodes:row([['특징 파이프라인','Feature pipeline'],['교차 검증','Cross-validation'],['설정 비교','Compare settings'],['최종 선택·테스트','Select · test once']]),edges:[[0,1],[1,2],[2,3]]},
 'ensembles':{title:['여러 학습기를 모아 더 강하게','Combine many learners'],caption:['여러 약한 모델의 예측을 결합합니다. 배깅은 분산을, 부스팅은 편향을 줄이는 방향으로 오류를 낮춥니다.','Combine several weak models. Bagging reduces variance; boosting reduces bias, lowering overall error.'],nodes:row([['여러 약한 학습기','Weak learners'],['배깅 / 부스팅','Bagging / boosting'],['투표 · 가중합','Vote · weighted sum'],['강한 예측','Stronger prediction']]),edges:[[0,1],[1,2],[2,3]]},
 'dimensionality-reduction':{title:['정보를 최대한 보존하며 차원 축소','Reduce dimensions, keep information'],caption:['PCA는 분산이 큰 방향(주성분)을 찾아 저차원으로 투영합니다. 시각화·잡음 제거에 쓰지만 축의 의미 해석에는 주의가 필요합니다.','PCA finds directions of greatest variance and projects onto them. Useful for visualization and denoising; interpret axes with care.'],nodes:row([['고차원 데이터','High-dim data'],['주성분 방향','Principal directions'],['저차원 투영','Project down'],['정보 최대 보존','Keep most variance']]),edges:[[0,1],[1,2],[2,3]]},
 'training-stability':{title:['학습을 안정시키는 장치들','Techniques that stabilize training'],caption:['입력·활성값 정규화, 좋은 초기화, 정규화 층과 잔차 연결이 기울기 흐름을 도와 깊은 신경망을 안정적으로 학습시킵니다.','Normalizing inputs/activations, good initialization, normalization layers and residual connections keep gradients flowing in deep nets.'],nodes:row([['입력 정규화','Normalize inputs'],['가중치 초기화','Initialize weights'],['정규화 층 · 잔차','Norm layers · residual'],['안정적 학습','Stable training']]),edges:[[0,1],[1,2],[2,3]]},
 'llm-training-lifecycle':{title:['사전학습에서 정렬까지','From pretraining to alignment'],caption:['대량 텍스트로 사전학습한 뒤 지도 미세조정(SFT)과 선호 학습(RLHF/DPO)으로 유용하고 안전한 응답으로 정렬합니다.','Pretrain on large text, then supervised fine-tuning (SFT) and preference learning (RLHF/DPO) align it toward useful, safe responses.'],nodes:row([['사전학습','Pretraining'],['지도 미세조정 SFT','SFT'],['선호 학습 RLHF/DPO','Preference learning'],['정렬된 모델','Aligned model']]),edges:[[0,1],[1,2],[2,3]]},
 'llm-evaluation-tools':{title:['도구 호출은 제안, 실행은 정책','Tool calls are proposals; policy executes'],caption:['작업과 성공 기준을 정하고, 모델은 스키마에 맞춘 도구 호출을 제안합니다. 권한 검사를 통과한 호출만 실행하고 결과를 검증합니다.','Define the task and success criteria; the model proposes schema-valid tool calls. Only permitted calls execute, and results are verified.'],nodes:row([['작업·성공 기준','Task · success criteria'],['스키마 도구 호출 제안','Propose tool call'],['권한 내 실행','Execute if permitted'],['결과 검증','Verify result']]),edges:[[0,1],[1,2],[2,3]]},
 'reinforcement-learning':{title:['에이전트–환경 상호작용 루프','The agent–environment loop'],caption:['에이전트가 상태를 보고 행동을 고르면 환경이 보상과 다음 상태를 돌려줍니다. 지연된 보상으로 정책을 조금씩 개선합니다.','The agent observes a state, chooses an action, and the environment returns a reward and next state. Delayed rewards gradually improve the policy.'],nodes:row([['상태 관찰','Observe state'],['정책이 행동 선택','Policy picks action'],['환경 보상·다음 상태','Reward · next state'],['정책 갱신','Update policy']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'generative-models':{title:['노이즈에서 표본으로','From noise to a sample'],caption:['GAN은 생성기와 판별기를 경쟁시키고, 확산 모델은 노이즈를 점진적으로 걷어 내 표본을 만듭니다. 품질은 별도 지표와 사람 평가로 확인합니다.','GANs pit a generator against a discriminator; diffusion models gradually denoise into a sample. Quality needs separate metrics and human review.'],nodes:row([['잠재 벡터 · 노이즈','Latent · noise'],['생성기 · 역확산','Generator · denoise'],['표본 생성','Generated sample'],['품질 평가','Assess quality']]),edges:[[0,1],[1,2],[2,3]]},
 'graph-neural-networks':{title:['이웃 정보를 모아 표현 갱신','Aggregate neighbours to update nodes'],caption:['각 노드가 이웃의 표현을 모아 자기 표현을 갱신합니다. 층을 쌓을수록 더 먼 이웃 정보까지 담기지만, 너무 깊으면 과평활화가 생깁니다.','Each node aggregates neighbour representations to update itself. More layers reach farther neighbours, but too many cause over-smoothing.'],nodes:row([['노드 + 이웃','Node + neighbours'],['이웃 정보 집계','Aggregate neighbours'],['표현 갱신','Update representation'],['여러 층 반복','Repeat layers']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'support-vector-machines':{title:['최대 여백 경계','The maximum-margin boundary'],caption:['SVM은 두 클래스 사이 여백이 가장 넓은 경계를 고르며, 경계는 가장자리의 소수 서포트 벡터로 결정됩니다. 커널로 비선형 경계도 다룹니다.','SVM picks the boundary with the widest margin, decided by a few support vectors at the edge. Kernels handle non-linear boundaries.'],nodes:[n(25,90,['두 클래스','Two classes']),n(240,90,['최대 여백 경계','Max-margin boundary'],'',185),n(510,25,['서포트 벡터가 결정','Support vectors decide'],'',195),n(510,155,['커널로 비선형','Kernels: non-linear'],'',195)],edges:[[0,1],[1,2],[1,3]],height:245},
 'autoencoders':{title:['압축했다 복원하며 배우기','Learn by compressing and reconstructing'],caption:['인코더가 병목으로 압축하고 디코더가 복원합니다. 정상으로 학습하면 이상 입력의 복원 오차가 커져 이상 점수로 쓸 수 있습니다.','An encoder compresses to a bottleneck and a decoder reconstructs. Trained on normal data, anomalies reconstruct poorly — a usable anomaly score.'],nodes:row([['입력','Input'],['인코더 → 병목','Encoder → bottleneck'],['디코더 → 복원','Decoder → reconstruct'],['복원 오차 = 이상 점수','Recon error = score']]),edges:[[0,1],[1,2],[2,3]]},
 'multimodal-models':{title:['서로 다른 모달리티를 한 공간에','Different modalities in one space'],caption:['텍스트와 이미지를 각 인코더로 벡터화해 같은 표현 공간에 정렬합니다. 그러면 교차 검색이나 제로샷 분류가 가능해집니다.','Text and image encoders map each modality into a shared space where they align, enabling cross-modal retrieval and zero-shot classification.'],nodes:[n(25,25,['텍스트 인코더','Text encoder'],'',185),n(25,150,['이미지 인코더','Image encoder'],'',185),n(300,90,['공통 표현 공간','Shared space'],'',180),n(560,90,['정렬 · 교차 검색','Align · retrieve'],'',160)],edges:[[0,2],[1,2],[2,3]],height:240},
 'recommender-systems':{title:['상호작용에서 선호 예측으로','From interactions to predicted preference'],caption:['사용자×항목 상호작용에서 유사도나 잠재 요인을 학습해 보지 않은 항목의 선호를 예측하고 상위를 추천합니다. 콜드 스타트·편향에 유의합니다.','Learn similarity or latent factors from user–item interactions to predict preference for unseen items and recommend the top ones. Mind cold start and bias.'],nodes:row([['사용자 × 항목','User × item'],['유사도 · 잠재 요인','Similarity · latent factors'],['선호 예측','Predict preference'],['상위 추천','Top-N recommend']]),edges:[[0,1],[1,2],[2,3]]}
});

Object.assign(configs,{
 'algorithms-union-find':{title:['유니온-파인드: 합치기와 대표 찾기','Union-find: union and find'],caption:['각 원소가 자기 그룹에서 시작해, union으로 그룹을 합치고 find로 대표(루트)를 찾습니다. 경로 압축과 크기 기준 합치기로 거의 상수 시간입니다.','Each element starts in its own set; union merges sets and find returns the representative. Path compression and union-by-size give near-constant time.'],nodes:row([['각자 자기 그룹','Each in its own set'],['union: 그룹 합치기','union: merge sets'],['find: 대표(루트)','find: root'],['압축 → 거의 O(1)','Compress → ~O(1)']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-two-pointers':{title:['투 포인터: 한 방향으로만 이동','Two pointers move one way'],caption:['정렬·단조 조건에서 두 포인터를 조건에 따라 진행시켜 이중 반복을 선형으로 줄입니다. 각 원소가 창에 최대 한 번 드나듭니다.','On sorted or monotone data, advance two pointers by condition to turn a double loop into linear time; each element enters and leaves once.'],nodes:row([['양 끝/한쪽 시작','Start at ends/left'],['조건 따라 이동','Move by condition'],['각 원소 최대 한 번','Each visited once'],['O(n) 달성','Achieve O(n)']]),edges:[[0,1],[1,2],[2,3]]},
 'algorithms-bit-manipulation':{title:['비트 마스크로 직접 다루기','Manipulate bits directly'],caption:['정수를 비트 묶음으로 보고 AND·OR·XOR·시프트로 특정 비트를 켜고 끄고 검사합니다. 플래그 집합과 빠른 계산에 유용합니다.','Treat an integer as bits and use AND/OR/XOR/shift to set, clear and test specific bits — handy for flag sets and fast computation.'],nodes:row([['정수 = 비트 묶음','Integer = bits'],['AND/OR/XOR/시프트','AND/OR/XOR/shift'],['켜기·끄기·검사','Set · clear · test'],['플래그·빠른 계산','Flags · fast math']]),edges:[[0,1],[1,2],[2,3]]},
 'cs-computability-complexity':{title:['풀 수 있는가, 빠르게 풀 수 있는가','Solvable, and solvable fast?'],caption:['어떤 문제는 아예 풀 수 없습니다(정지 문제). 풀 수 있는 문제는 P(빠르게 풀림)·NP(빠르게 검증)로 나뉘고, NP-완전이면 근사·휴리스틱으로 방향을 틉니다.','Some problems are unsolvable (halting). Solvable ones split into P (solved fast) and NP (verified fast); NP-complete ones call for approximation or heuristics.'],nodes:row([['문제','A problem'],['계산 가능?','Computable?'],['P: 풀림 · NP: 검증','P: solve · NP: verify'],['NP-완전 → 근사','NP-complete → approx']]),edges:[[0,1],[1,2],[2,3]]},
 'model-efficiency':{title:['큰 모델을 가볍게','Make a big model smaller'],caption:['양자화(정밀도↓)·프루닝(가중치 제거)·증류(작은 모델로 지식 이전)로 지연·메모리·비용을 줄입니다. 압축 뒤 정확도 손실을 반드시 검증합니다.','Quantization, pruning and distillation cut latency, memory and cost. Always verify the accuracy loss after compression.'],nodes:row([['큰 모델','Large model'],['양자화·프루닝·증류','Quantize · prune · distill'],['작고 빠른 모델','Small fast model'],['정확도 손실 검증','Verify accuracy loss']]),edges:[[0,1],[1,2],[2,3]]},
 'ai-agents':{title:['에이전트 루프','The agent loop'],caption:['목표를 향해 관찰→계획·도구 선택→(정책 검증 후) 실행→결과 반영을 반복합니다. 단계 한도와 권한 검증으로 오류 누적·폭주를 막습니다.','Toward a goal: observe, plan/choose a tool, execute (after policy checks), and fold results back — with step limits and permission checks to prevent runaway.'],nodes:row([['목표·상태 관찰','Observe goal/state'],['계획·도구 선택','Plan · choose tool'],['정책 검증 후 실행','Execute if allowed'],['결과 반영·반복','Fold result · repeat']]),edges:[[0,1],[1,2],[2,3]],loop:true},
 'vulnerabilities-nosql-ldap-injection':{title:['값 자리에 구조가 들어오면','When structure enters a value slot'],caption:['입력이 값이어야 할 자리에 쿼리 연산자나 필터 메타문자로 들어오면 질의 논리가 바뀝니다. 타입 강제와 이스케이프로 값으로만 취급합니다.','If input arrives as a query operator or filter metacharacter where a value belongs, it changes the query logic. Enforce types and escape so it stays a value.'],nodes:row([['사용자 입력','User input'],['연산자/메타문자','Operator/metachar'],['질의 구조 변형','Query logic altered'],['타입 강제·이스케이프','Type-check · escape']]),edges:[[0,1],[1,2],[0,3]]},
 'vulnerabilities-mass-assignment':{title:['통째 바인딩이 만드는 구멍','The gap from binding everything'],caption:['요청 본문을 모델에 통째로 바인딩하면 권한·소유자 같은 예상 밖 필드까지 설정됩니다. 수정 가능한 필드를 허용 목록으로 명시해 막습니다.','Binding the whole request body sets unintended fields like role or owner. Restrict updatable fields with an explicit allowlist.'],nodes:row([['요청 본문 전체','Whole request body'],['모델에 통째 바인딩','Bind everything'],['예상 밖 필드 설정','Unintended fields set'],['허용 목록으로 제한','Allowlist fields']]),edges:[[0,1],[1,2],[0,3]]}
});

Object.assign(configs,{
 'security-for-ai-securing-ai-systems':{title:['AI 시스템의 신뢰 경계','Trust boundaries of an AI system'],caption:['학습 데이터·모델·입력·출력·도구를 모두 신뢰할 수 없는 것으로 보고, 각 경계에서 검증과 권한을 강제합니다. 정확도 지표는 정상 상황만 말합니다.','Treat data, model, input, output and tools as untrusted, enforcing checks and permissions at each boundary. Accuracy reflects only the benign case.'],nodes:row([['학습 데이터','Training data'],['모델','Model'],['입력·출력','Input · output'],['도구·권한','Tools · permissions']]),edges:[[0,1],[1,2],[2,3]]},
 'security-for-ai-data-poisoning':{title:['소수 오염이 백도어를 심는다','A little poison plants a backdoor'],caption:['학습 데이터 일부에 트리거+목표 라벨을 심으면, 평소엔 정상이지만 트리거가 있을 때만 오작동하는 백도어가 생깁니다. 정확도로는 안 보입니다.','Planting a trigger with a target label in a fraction of the data yields a backdoor: normal usually, malicious only on the trigger — invisible to accuracy.'],nodes:row([['학습 데이터','Training data'],['소수 샘플 오염','Poison a few'],['트리거+목표 라벨','Trigger + target'],['트리거에만 오작동','Fires on trigger']]),edges:[[0,1],[1,2],[2,3]]},
 'security-for-ai-model-extraction':{title:['질의만으로 복제하기','Cloning through queries'],caption:['입력을 넣고 출력을 대량으로 관찰하면 동작을 모사한 대리 모델이 만들어집니다. 응답을 최소화하고 질의를 제한해 완화합니다.','Feeding inputs and observing many outputs builds a surrogate that mimics behaviour. Minimize responses and limit queries to mitigate.'],nodes:row([['반복 질의','Repeated queries'],['입력–출력 수집','Collect I/O pairs'],['대리 모델 학습','Train surrogate'],['응답 최소화·제한','Minimize · throttle']]),edges:[[0,1],[1,2],[0,3]]},
 'security-for-ai-data-privacy-ml':{title:['모델이 기억한 것이 새어 나온다','Memorized data leaks out'],caption:['과적합·반복 노출로 모델이 샘플을 기억하면, 확신도 차이로 멤버십을 추론하거나 학습 문장을 추출할 수 있습니다. 차등 프라이버시로 완화합니다.','Overfit or repeated samples get memorized, enabling membership inference from confidence gaps or extraction of training text. Differential privacy mitigates.'],nodes:row([['학습 데이터 기억','Memorized data'],['확신도 차이','Confidence gap'],['멤버십·추출','Inference · extraction'],['차등 프라이버시','Differential privacy']]),edges:[[0,1],[1,2],[0,3]]},
 'security-for-ai-llm-application-security':{title:['입력과 출력 모두 신뢰 경계','Both input and output are boundaries'],caption:['모델 입력은 인젝션 표면, 출력은 실행·렌더 시 XSS·주입 표면입니다. 출력을 데이터로 취급해 검증하고, 도구 권한을 좁혀 과도한 권한을 막습니다.','Model input is an injection surface; output is an XSS/injection surface when executed or rendered. Validate output as data and scope tool permissions.'],nodes:[n(25,90,['모델','Model']),n(230,25,['입력: 인젝션 표면','Input: injection'],'',195),n(230,155,['출력: 실행/렌더 검증','Output: validate'],'',205),n(555,90,['도구 권한 최소화','Least-privilege tools'],'',170)],edges:[[1,0],[0,2],[0,3]],height:245},
 'security-for-ai-ml-supply-chain':{title:['외부 모델·데이터를 그대로 믿지 않기','Do not trust external models/data blindly'],caption:['pickle 모델은 로드만으로 코드가 실행될 수 있습니다. 출처·다이제스트를 검증하고 safetensors 같은 실행 불가 포맷과 격리 로드를 씁니다.','A pickle model can run code on load. Verify provenance and digests, and use non-executable formats like safetensors with isolated loading.'],nodes:row([['외부 모델·데이터','External model/data'],['출처·다이제스트 검증','Verify provenance'],['안전 포맷·격리','Safe format · isolate'],['파이프라인 반영','Into pipeline']]),edges:[[0,1],[1,2],[2,3]]},
 'security-for-ai-ai-red-teaming':{title:['적대적 관점의 지속 검증','Continuous adversarial testing'],caption:['배포 전·후로 인젝션·회피·유해 출력·탈옥을 능동적으로 시도하고, 찾은 실패를 회귀 테스트로 남겨 변경마다 재실행합니다. 거버넌스로 체계화합니다.','Actively try injection, evasion, harmful output and jailbreaks before and after release; capture failures as regression tests re-run on every change, under governance.'],nodes:row([['적대적 시도','Adversarial attempts'],['실패 발견','Find failures'],['회귀 테스트화','Turn into tests'],['변경마다 재실행','Re-run on change']]),edges:[[0,1],[1,2],[2,3]],loop:true}
});
