import {renderTLDR} from './research-tldr.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={autonomy:['자율주행','Autonomous driving'],vehicle:['차량 보안','Vehicle security'],ros:['ROS·미들웨어','ROS & middleware'],physical:['Physical AI·로봇','Physical AI & robotics']};
export function setupRoboticsArchive(container,data,lang){
 const t=(ko,en)=>lang==='en'?en:ko;
 if(!data){container.innerHTML=`<p class="feed-warning">${t('학회 아카이브를 아직 불러오지 못했습니다.','Conference archive is not available yet.')}</p>`;return;}
 const sources=data.sources||[],items=[...(data.items||[])].sort((a,b)=>b.year-a.year||a.venue.localeCompare(b.venue)||a.title.localeCompare(b.title,'en'));
 const venues=[...new Map(sources.map(s=>[s.id,s.name])).entries()],years=[...new Set(items.map(i=>i.year))].sort((a,b)=>b-a);
 let venue='all',year='all',topic='all',query='',visible=20;
 const options=entries=>entries.map(([value,label])=>`<option value="${escape(value)}">${escape(label)}</option>`).join('');
 container.innerHTML=`<div class="section-head"><h2>${t('보안 학회 아카이브','Security conference archive')}</h2><span>${t('학회 연도 최신순','Newest conference year first')}</span></div><p class="research-note">${t('IEEE S&P · USENIX Security · ACM CCS · NDSS · VehicleSec의 2025년 이후 공식 논문 목록과 NDSS 2024의 관련 제목을 선별합니다. Physical AI는 로봇·무인기·센서·물리 환경의 AI 보안을 포함합니다. 같은 연도는 학회·제목순이며 개별 게시일을 의미하지 않습니다. 아래 뉴스 검색·기간 필터와 별도로 검색합니다.','Related titles from official IEEE S&P, USENIX Security, ACM CCS, NDSS and VehicleSec lists since 2025, plus NDSS 2024. Physical AI includes robotics, drones, sensors and AI in physical environments. Within a year, entries sort by venue and title, not individual publication dates. Archive filters are separate from the news filters below.')}</p><div class="search-wrap"><span class="search-icon" aria-hidden="true">⌕</span><input id="archive-search" type="search" aria-label="${t('학회 논문 검색','Search conference papers')}" placeholder="${t('논문 제목·요약 검색','Search paper titles and summaries')}"></div><div class="archive-filters"><label>${t('학회','Conference')} <select id="archive-venue">${options([['all',t('전체 학회','All conferences')],...venues])}</select></label><label>${t('연도','Year')} <select id="archive-year">${options([['all',t('전체 연도','All years')],...years.map(y=>[y,y])])}</select></label><label>${t('주제','Topic')} <select id="archive-topic">${options([['all',t('전체 주제','All topics')],...Object.entries(labels).map(([id,names])=>[id,t(...names)])])}</select><span id="archive-count" aria-live="polite"></span></label></div><div class="archive-results"></div><details class="archive-sources"><summary>${t('수집 범위·출처 상태','Coverage and source status')}</summary><p class="research-note">${t('목록이 바뀌거나 수집에 실패해도 기존 기록을 유지합니다. 신규 채택 목록은 완성 전일 수 있고, 키워드 선별에는 누락·오분류가 있을 수 있습니다.','Saved papers remain when a source changes or collection fails. Acceptance lists may be incomplete; keyword selection can miss or misclassify papers.')}</p>${sources.map(s=>`<p><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.name)} ${s.year} ↗</a> · ${s.status==='ok'?t(`${s.matched_count}건 확인`,`${s.matched_count} matches`):t('수집 확인 필요 · 저장 목록 유지','Update needs attention; saved entries retained')} · ${t('최근 성공','Last success')}: ${escape(s.last_success?.slice(0,10)||'—')}</p>`).join('')}</details>`;
 function update(reset=true){
  if(reset)visible=20;
  const matches=items.filter(i=>(venue==='all'||i.venue===venue)&&(year==='all'||String(i.year)===year)&&(topic==='all'||i.tags.includes(topic))&&[i.title,i.tldr?.ko,i.tldr?.en].filter(Boolean).join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  container.querySelector('#archive-count').textContent=t(`${matches.length}편`,`${matches.length} papers`);
  container.querySelector('.archive-results').innerHTML=matches.length?matches.slice(0,visible).map(i=>`<article class="conference-paper archive-paper" data-year="${i.year}" data-venue="${escape(i.venue)}"><div class="research-item-meta"><span>${escape(venues.find(([id])=>id===i.venue)?.[1]||i.venue)}</span><span>${i.year} · ${t('학회 연도','Conference year')}</span></div><h3><a href="${escape(i.url)}" lang="en" target="_blank" rel="noopener noreferrer">${escape(i.title)} ↗</a></h3>${i.tldr?.ko||i.tldr?.en?renderTLDR(i,lang):''}<div class="research-tags">${i.tags.map(tag=>`<span>${escape(t(...labels[tag]))}</span>`).join('')}</div></article>`).join(''):`<div class="empty">${t('조건에 맞는 학회 논문이 없습니다. 검색어나 필터를 바꿔보세요.','No matching conference papers. Try another search or filter.')}</div>`;
  if(matches.length>visible){const button=document.createElement('button');button.className='chip archive-more';button.textContent=t(`더 보기 (${matches.length-visible}편 남음)`,`Show more (${matches.length-visible} remaining)`);button.addEventListener('click',()=>{const start=visible;visible+=20;update(false);container.querySelectorAll('.archive-paper h3 a')[start]?.focus();});container.querySelector('.archive-results').append(button);}
 }
 container.querySelector('#archive-search').addEventListener('input',e=>{query=e.target.value;update();});
 container.querySelector('#archive-venue').addEventListener('change',e=>{venue=e.target.value;update();});
 container.querySelector('#archive-year').addEventListener('change',e=>{year=e.target.value;update();});
 container.querySelector('#archive-topic').addEventListener('change',e=>{topic=e.target.value;update();});update();
}
